# Will be used by buildkite pipeline
version: '3.7'
services:
  main:
    build:
      context: .
      dockerfile: Dockerfile
      target: build
    image: embedded-react-sdk:main
    environment:
      - BUILDKITE=${BUILDKITE}
      - BUILDKITE_BRANCH=${BUILDKITE_BRANCH}
      - BUILDKITE_PIPELINE_DEFAULT_BRANCH=${BUILDKITE_PIPELINE_DEFAULT_BRANCH}
      - BUILDKITE_BUILD_CHECKOUT_PATH=${BUILDKITE_BUILD_CHECKOUT_PATH}
      - BUILDKITE_BUILD_NUMBER=${BUILDKITE_BUILD_NUMBER}
      - BUILDKITE_BUILD_URL=${BUILDKITE_BUILD_URL}
      - BUILDKITE_COMMIT=${BUILDKITE_COMMIT}
      - BUILDKITE_ORGANIZATION_SLUG=${BUILDKITE_ORGANIZATION_SLUG}
      - BUILDKITE_PULL_REQUEST=${BUILDKITE_PULL_REQUEST}
      - BUILDKITE_PULL_REQUEST_BASE_BRANCH=${BUILDKITE_PULL_REQUEST_BASE_BRANCH}
      - BUILDKITE_TAG=${BUILDKITE_TAG}
      - GH_TOKEN=${GH_TOKEN}
      - NPM_TOKEN=${NPM_TOKEN}
      - PERCY_TOKEN=${PERCY_TOKEN}
    volumes:
      - ~/.npmrc:/root/.npmrc
