/**
 * Shared demo provisioning logic used by both the CLI setup script
 * and the Vite dev server middleware. Centralizes the gws-flows
 * demo creation, flow token polling, and env file generation.
 */
import { mkdirSync, writeFileSync } from 'fs'
import { dirname } from 'path'
import {
  fetchEntityIds,
  fetchCompanyId,
  ENTITY_ID_KEYS,
  entityIdToEnvVar,
} from '../src/entity-config'

const ALLOWED_ORIGINS = new Set([
  'https://flows.gusto-demo.com',
  'https://flows.gusto-staging.com',
  'http://localhost:7777',
  'http://localhost:3000',
])

/**
 * Validates a host URL against the allowlist and returns the
 * sanitized origin. Throws if the host is not allowed.
 */
export function validateHost(host: string): string {
  let parsed: URL
  try {
    parsed = new URL(host)
  } catch {
    throw new Error(`Invalid host URL: ${host}`)
  }

  if (!['http:', 'https:'].includes(parsed.protocol)) {
    throw new Error(`Only http/https protocols are allowed: ${host}`)
  }

  if (!ALLOWED_ORIGINS.has(parsed.origin) && parsed.hostname !== 'localhost') {
    throw new Error(`Disallowed host: ${host}. Allowed: ${[...ALLOWED_ORIGINS].join(', ')}`)
  }

  return parsed.origin
}

export function isAllowedHost(host: string): boolean {
  try {
    validateHost(host)
    return true
  } catch {
    return false
  }
}

export interface DemoResult {
  flowToken: string
  companyId: string
  entities: Partial<Record<string, string>>
  demoType: string
}

export async function createDemoAndProvision(
  gwsFlowsHost: string,
  demoType: string,
  options: { maxPollAttempts?: number; onProgress?: (msg: string) => void } = {},
): Promise<DemoResult> {
  const { maxPollAttempts = 60, onProgress } = options

  const safeHost = validateHost(gwsFlowsHost)
  onProgress?.(`Creating ${demoType} demo at ${safeHost}...`)

  const formBody = new URLSearchParams({
    'demo[flow_type]': demoType,
    'demo[admin_name]': 'SDK Dev',
    'demo[email]': `sdk-dev-${Date.now()}@example.com`,
    'demo[company_name]': `SDK Dev ${new Date().toISOString().slice(0, 10)}`,
  })

  const createRes = await fetch(`${safeHost}/demos`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
    body: formBody.toString(),
    redirect: 'follow',
  })

  if (!createRes.ok && createRes.status !== 302 && createRes.status !== 303) {
    const text = await createRes.text().catch(() => '')
    throw new Error(`Demo creation failed: ${createRes.status} ${createRes.statusText}\n${text}`)
  }

  const demoIdMatch =
    createRes.url.match(/\/demos\/([a-f0-9-]+)/) ||
    (await createRes.text().catch(() => '')).match(/\/demos\/([a-f0-9-]+)/)

  if (!demoIdMatch) {
    throw new Error(`Could not extract demo ID from response URL: ${createRes.url}`)
  }

  const demoId = demoIdMatch[1]
  onProgress?.(`Demo created: ${demoId}`)

  onProgress?.('Waiting for demo to be ready...')
  let flowToken = ''
  for (let attempt = 1; attempt <= maxPollAttempts; attempt++) {
    await new Promise(r => setTimeout(r, 3000))

    try {
      const pollRes = await fetch(`${safeHost}/demos/${demoId}`, {
        signal: AbortSignal.timeout(10000),
      })
      const html = await pollRes.text()
      const linkMatch = html.match(/https?:\/\/[^"]*\/flows\/([a-zA-Z0-9_-]{20,})/)
      if (linkMatch) {
        flowToken = linkMatch[1]
        break
      }
    } catch {
      // Transient fetch errors during polling are expected
    }

    if (attempt % 5 === 0) {
      onProgress?.(`Still waiting... (${attempt * 3}s)`)
    }
  }

  if (!flowToken) {
    throw new Error(`Demo creation timed out after ${maxPollAttempts * 3}s`)
  }

  onProgress?.(`Flow token: ${flowToken.slice(0, 15)}...`)

  const proxyBase = `${safeHost}/fe_sdk/${flowToken}`
  const companyId = await fetchCompanyId(proxyBase)
  if (companyId) {
    onProgress?.(`Company ID: ${companyId}`)
  }

  let entities: Partial<Record<string, string>> = {}
  if (companyId) {
    onProgress?.('Fetching entity IDs...')
    entities = await fetchEntityIds(proxyBase, companyId)
  }

  return { flowToken, companyId, entities, demoType }
}

export function writeEnvFile(envPath: string, result: DemoResult & { gwsFlowsHost: string }) {
  const entityLines = ENTITY_ID_KEYS.map(
    key => `${entityIdToEnvVar(key)}=${result.entities[key] || ''}`,
  )

  const content = [
    `# Auto-generated by sdk-app on ${new Date().toISOString()}`,
    '',
    `GWS_FLOWS_HOST=${result.gwsFlowsHost}`,
    `FLOW_TOKEN=${result.flowToken}`,
    `VITE_COMPANY_ID=${result.companyId}`,
    ...entityLines,
    `VITE_REQUEST_ID=`,
    `VITE_DEMO_TYPE=${result.demoType}`,
    '',
  ].join('\n')

  mkdirSync(dirname(envPath), { recursive: true })
  writeFileSync(envPath, content)
}
