/* eslint-disable no-console */
import { resolve } from 'path'
import { writeFileSync } from 'fs'
import { Project, SyntaxKind, type Type } from 'ts-morph'

const ROOT = resolve(import.meta.dirname, '../..')
const OUTPUT = resolve(import.meta.dirname, '../src/generated-registry-data.ts')

const STANDARD_PROPS = new Set([
  'children',
  'className',
  'defaultValues',
  'dictionary',
  'FallbackComponent',
  'LoaderComponent',
  'onEvent',
])

const ENTITY_ID_PROPS = new Set([
  'companyId',
  'companyUuid',
  'employeeId',
  'contractorId',
  'payrollId',
  'requestId',
])

const NAMESPACES: Record<string, string> = {
  Company: 'src/components/Company/index.tsx',
  Employee: 'src/components/Employee/index.ts',
  Contractor: 'src/components/Contractor/index.ts',
  Payroll: 'src/components/Payroll/index.ts',
  InformationRequests: 'src/components/InformationRequests/index.ts',
}

interface ComponentData {
  requiredEntityIds: string[]
  additionalRequiredProps: string[]
}

function getRequiredProps(type: Type): string[] {
  const props: string[] = []
  for (const prop of type.getProperties()) {
    const declarations = prop.getDeclarations()
    const isOptional = declarations.some(d => {
      if (d.isKind(SyntaxKind.PropertySignature)) {
        return d.hasQuestionToken()
      }
      return false
    })

    if (!isOptional) {
      props.push(prop.getName())
    }
  }
  return props
}

function analyzeComponents(): Record<string, ComponentData> {
  const project = new Project({
    tsConfigFilePath: resolve(ROOT, 'tsconfig.json'),
    skipAddingFilesFromTsConfig: true,
  })

  const results: Record<string, ComponentData> = {}

  for (const [namespace, indexPath] of Object.entries(NAMESPACES)) {
    const fullPath = resolve(ROOT, indexPath)
    const sourceFile = project.addSourceFileAtPath(fullPath)

    for (const exportDecl of sourceFile.getExportDeclarations()) {
      for (const namedExport of exportDecl.getNamedExports()) {
        const name = namedExport.getName()
        const key = `${namespace}.${name}`

        const symbol = namedExport.getNameNode().getSymbol()
        if (!symbol) continue

        const aliasedSymbol = symbol.getAliasedSymbol()
        const targetSymbol = aliasedSymbol || symbol

        const declarations = targetSymbol.getDeclarations()
        const funcDecl = declarations.find(
          d => d.isKind(SyntaxKind.FunctionDeclaration) || d.isKind(SyntaxKind.VariableDeclaration),
        )

        if (!funcDecl) continue

        let propsType: Type | undefined

        if (funcDecl.isKind(SyntaxKind.FunctionDeclaration)) {
          const params = funcDecl.getParameters()
          if (params.length > 0) {
            propsType = params[0].getType()
          }
        } else if (funcDecl.isKind(SyntaxKind.VariableDeclaration)) {
          const initializer = funcDecl.getInitializer()
          if (
            initializer &&
            (initializer.isKind(SyntaxKind.ArrowFunction) ||
              initializer.isKind(SyntaxKind.FunctionExpression))
          ) {
            const params = initializer.getParameters()
            if (params.length > 0) {
              propsType = params[0].getType()
            }
          }
        }

        if (!propsType) continue

        const allRequired = getRequiredProps(propsType)
        const entityIds: string[] = []
        const additionalProps: string[] = []

        for (const prop of allRequired) {
          if (STANDARD_PROPS.has(prop)) continue
          if (ENTITY_ID_PROPS.has(prop)) {
            entityIds.push(prop)
          } else {
            additionalProps.push(prop)
          }
        }

        results[key] = {
          requiredEntityIds: entityIds.length > 0 ? entityIds : ['companyId'],
          additionalRequiredProps: additionalProps,
        }
      }
    }
  }

  return results
}

function generate() {
  console.log('Analyzing component interfaces...\n')

  const results = analyzeComponents()
  const sortedKeys = Object.keys(results).sort()

  let output = `// Auto-generated by sdk-app/scripts/generate-registry.ts\n`
  output += `// Run: npx tsx sdk-app/scripts/generate-registry.ts\n\n`

  output += `export const ENTITY_REQUIREMENTS: Record<string, string[]> = {\n`
  for (const key of sortedKeys) {
    const ids = JSON.stringify(results[key].requiredEntityIds)
    output += `  '${key}': ${ids},\n`
  }
  output += `}\n\n`

  output += `export const ADDITIONAL_REQUIRED_PROPS: Record<string, string[]> = {\n`
  for (const key of sortedKeys) {
    const props = results[key].additionalRequiredProps
    if (props.length > 0) {
      output += `  '${key}': ${JSON.stringify(props)},\n`
    }
  }
  output += `}\n`

  writeFileSync(OUTPUT, output)
  console.log(`Generated: ${OUTPUT}`)
  console.log(`  ${sortedKeys.length} components analyzed`)

  const withAdditional = sortedKeys.filter(k => results[k].additionalRequiredProps.length > 0)
  if (withAdditional.length > 0) {
    console.log(`  ${withAdditional.length} with additional required props:`)
    for (const key of withAdditional) {
      console.log(`    ${key}: ${results[key].additionalRequiredProps.join(', ')}`)
    }
  }
}

generate()
