/* eslint-disable no-console */
import { writeFileSync } from 'fs'
import { resolve } from 'path'
import {
  fetchEntityIds,
  fetchCompanyId,
  ENTITY_ID_KEYS,
  entityIdToEnvVar,
} from '../src/entity-config'

const ENV_DIR = resolve(import.meta.dirname, '../env')

const ENV_DEFAULTS: Record<string, string> = {
  demo: 'https://flows.gusto-demo.com',
  staging: 'https://flows.gusto-staging.com',
  localzp: 'http://localhost:7777',
}

const ALLOWED_HOSTS = new Set([
  'https://flows.gusto-demo.com',
  'https://flows.gusto-staging.com',
  'http://localhost:7777',
  'http://localhost:3000',
])

function validateHost(host: string): void {
  try {
    const url = new URL(host)
    const origin = url.origin
    if (!ALLOWED_HOSTS.has(origin) && !url.hostname.match(/^localhost$/)) {
      throw new Error(`Disallowed host: ${host}. Allowed: ${[...ALLOWED_HOSTS].join(', ')}`)
    }
  } catch (e) {
    if (e instanceof Error && e.message.startsWith('Disallowed')) throw e
    throw new Error(`Invalid host URL: ${host}`)
  }
}

async function createDemo(
  gwsFlowsHost: string,
  demoType: string,
): Promise<{ flowToken: string; demoId: string }> {
  validateHost(gwsFlowsHost)
  console.log(`  Creating ${demoType} demo at ${gwsFlowsHost}...`)

  const formBody = new URLSearchParams({
    'demo[flow_type]': demoType,
    'demo[admin_name]': 'SDK Dev',
    'demo[email]': `sdk-dev-${Date.now()}@example.com`,
    'demo[company_name]': `SDK Dev ${new Date().toISOString().slice(0, 10)}`,
  })

  const createRes = await fetch(`${gwsFlowsHost}/demos`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
    body: formBody.toString(),
    redirect: 'follow',
  })

  if (!createRes.ok && createRes.status !== 302 && createRes.status !== 303) {
    const text = await createRes.text().catch(() => '')
    throw new Error(`Demo creation failed: ${createRes.status} ${createRes.statusText}\n${text}`)
  }

  const responseUrl = createRes.url
  const demoIdMatch = responseUrl.match(/\/demos\/([a-f0-9-]+)/)
  if (!demoIdMatch) {
    const html = await createRes.text().catch(() => '')
    const fallbackMatch = html.match(/\/demos\/([a-f0-9-]+)/)
    if (fallbackMatch) {
      return { flowToken: '', demoId: fallbackMatch[1] }
    }
    throw new Error(`Could not extract demo ID from response URL: ${responseUrl}`)
  }

  return { flowToken: '', demoId: demoIdMatch[1] }
}

async function pollForFlowToken(
  gwsFlowsHost: string,
  demoId: string,
  maxAttempts = 60,
): Promise<string> {
  console.log(`  Waiting for demo to be ready...`)

  for (let attempt = 1; attempt <= maxAttempts; attempt++) {
    await new Promise(r => setTimeout(r, 3000))

    try {
      const res = await fetch(`${gwsFlowsHost}/demos/${demoId}`, {
        signal: AbortSignal.timeout(10000),
      })
      const html = await res.text()

      const linkMatch = html.match(/https?:\/\/[^"]*\/flows\/([a-zA-Z0-9_-]{20,})/)
      if (linkMatch) {
        return linkMatch[1]
      }
    } catch {
      // Transient fetch errors during polling are expected
    }

    if (attempt % 5 === 0) {
      console.log(`    Still waiting... (${attempt * 3}s)`)
    }
  }

  throw new Error(`Demo creation timed out after ${maxAttempts * 3}s`)
}

function writeEnvFile(envPath: string, data: Record<string, string>) {
  const entityLines = ENTITY_ID_KEYS.map(key => `${entityIdToEnvVar(key)}=${data[key] || ''}`)

  const content = [
    `# Auto-generated by sdk-app:setup on ${new Date().toISOString()}`,
    '',
    `GWS_FLOWS_HOST=${data.gwsFlowsHost}`,
    `FLOW_TOKEN=${data.flowToken}`,
    `VITE_COMPANY_ID=${data.companyId}`,
    ...entityLines,
    `VITE_REQUEST_ID=`,
    `VITE_DEMO_TYPE=${data.demoType}`,
    '',
  ].join('\n')

  writeFileSync(envPath, content)
}

async function main() {
  const zpEnv = process.env.npm_config_env || 'demo'
  const demoType = process.env.npm_config_demo_type || 'react_sdk_demo_company_onboarded'

  console.log(`\n  SDK Dev App Setup`)
  console.log(`  Environment: ${zpEnv}\n`)

  const actualEnv = zpEnv === 'local' ? 'localzp' : zpEnv

  const envPath = resolve(ENV_DIR, `.env.${actualEnv}`)
  const gwsFlowsHost = ENV_DEFAULTS[actualEnv]

  if (!gwsFlowsHost) {
    console.error(`  Error: Unknown environment "${zpEnv}"`)
    console.error(`  Known environments: ${Object.keys(ENV_DEFAULTS).join(', ')}\n`)
    process.exit(1)
  }

  console.log(`  GWS-Flows host: ${gwsFlowsHost}`)
  console.log(`  Demo type: ${demoType}\n`)

  console.log(`  Checking connectivity...`)
  try {
    const healthRes = await fetch(`${gwsFlowsHost}/demos`, {
      signal: AbortSignal.timeout(15000),
    })
    if (!healthRes.ok && healthRes.status !== 404) {
      console.warn(`  Warning: GWS-Flows returned status ${healthRes.status}`)
    } else {
      console.log(`  GWS-Flows is reachable\n`)
    }
  } catch (err) {
    console.error(`  Error: Cannot reach ${gwsFlowsHost}`)
    console.error(`  ${err}\n`)
    process.exit(1)
  }

  const { demoId } = await createDemo(gwsFlowsHost, demoType)
  console.log(`  Demo created: ${demoId}`)

  const flowToken = await pollForFlowToken(gwsFlowsHost, demoId)
  console.log(`  Flow token: ${flowToken.slice(0, 15)}...`)

  const proxyBase = `${gwsFlowsHost}/fe_sdk/${flowToken}`
  const companyId = await fetchCompanyId(proxyBase)
  if (companyId) {
    console.log(`  Company ID: ${companyId}`)
  } else {
    console.warn(`  Warning: Could not fetch company ID`)
  }

  let entities: Partial<Record<string, string>> = {}
  if (companyId) {
    console.log(`  Fetching entity IDs...`)
    entities = await fetchEntityIds(proxyBase, companyId)

    for (const key of ENTITY_ID_KEYS) {
      if (entities[key]) console.log(`  ${key}: ${entities[key]}`)
    }
  }

  writeEnvFile(envPath, {
    gwsFlowsHost,
    flowToken,
    companyId,
    demoType,
    ...entities,
  })

  console.log(`\n  Environment file written: ${envPath}`)
  console.log(`\n  Setup complete! Run: npm run sdk-app-dev --env=${zpEnv}\n`)
}

main().catch((err: unknown) => {
  console.error(`\n  Setup failed: ${String(err)}\n`)
  process.exit(1)
})
