/* eslint-disable no-console */
import { existsSync, readFileSync, writeFileSync } from 'fs'
import { resolve } from 'path'

const ENV_DIR = resolve(import.meta.dirname, '../env')

const ENV_DEFAULTS: Record<string, string> = {
  demo: 'https://flows.gusto-demo.com',
  staging: 'https://flows.gusto-staging.com',
  localzp: 'http://localhost:7777',
}

function loadEnvFile(path: string): Record<string, string> {
  if (!existsSync(path)) return {}
  const content = readFileSync(path, 'utf-8')
  const vars: Record<string, string> = {}
  for (const line of content.split('\n')) {
    const trimmed = line.trim()
    if (!trimmed || trimmed.startsWith('#')) continue
    const eqIndex = trimmed.indexOf('=')
    if (eqIndex === -1) continue
    vars[trimmed.slice(0, eqIndex).trim()] = trimmed.slice(eqIndex + 1).trim()
  }
  return vars
}

async function createDemo(
  gwsFlowsHost: string,
  demoType: string,
): Promise<{ flowToken: string; demoId: string }> {
  console.log(`  Creating ${demoType} demo at ${gwsFlowsHost}...`)

  const formBody = new URLSearchParams({
    'demo[flow_type]': demoType,
    'demo[admin_name]': 'SDK Dev',
    'demo[email]': `sdk-dev-${Date.now()}@example.com`,
    'demo[company_name]': `SDK Dev ${new Date().toISOString().slice(0, 10)}`,
  })

  const createRes = await fetch(`${gwsFlowsHost}/demos`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
    body: formBody.toString(),
    redirect: 'follow',
  })

  if (!createRes.ok && createRes.status !== 302 && createRes.status !== 303) {
    const text = await createRes.text().catch(() => '')
    throw new Error(`Demo creation failed: ${createRes.status} ${createRes.statusText}\n${text}`)
  }

  const responseUrl = createRes.url
  const demoIdMatch = responseUrl.match(/\/demos\/([a-f0-9-]+)/)
  if (!demoIdMatch) {
    const html = await createRes.text().catch(() => '')
    const fallbackMatch = html.match(/\/demos\/([a-f0-9-]+)/)
    if (fallbackMatch) {
      return { flowToken: '', demoId: fallbackMatch[1] }
    }
    throw new Error(`Could not extract demo ID from response URL: ${responseUrl}`)
  }

  return { flowToken: '', demoId: demoIdMatch[1] }
}

async function pollForFlowToken(
  gwsFlowsHost: string,
  demoId: string,
  maxAttempts = 60,
): Promise<string> {
  console.log(`  Waiting for demo to be ready...`)

  for (let attempt = 1; attempt <= maxAttempts; attempt++) {
    await new Promise(r => setTimeout(r, 3000))

    try {
      const res = await fetch(`${gwsFlowsHost}/demos/${demoId}`, {
        signal: AbortSignal.timeout(10000),
      })
      const html = await res.text()

      const linkMatch = html.match(/https?:\/\/[^"]*\/flows\/([a-zA-Z0-9_-]{20,})/)
      if (linkMatch) {
        return linkMatch[1]
      }
    } catch {
      // Transient fetch errors during polling are expected
    }

    if (attempt % 5 === 0) {
      console.log(`    Still waiting... (${attempt * 3}s)`)
    }
  }

  throw new Error(`Demo creation timed out after ${maxAttempts * 3}s`)
}

async function fetchCompanyId(gwsFlowsHost: string, flowToken: string): Promise<string> {
  try {
    const res = await fetch(`${gwsFlowsHost}/fe_sdk/${flowToken}/v1/companies`, {
      signal: AbortSignal.timeout(10000),
    })
    if (res.ok) {
      const companies = await res.json()
      if (Array.isArray(companies) && companies.length > 0) {
        return companies[0].uuid
      }
    }
  } catch {
    // Will return empty string
  }
  return ''
}

async function fetchEntityIds(
  gwsFlowsHost: string,
  flowToken: string,
  companyId: string,
): Promise<Record<string, string>> {
  const entities: Record<string, string> = {}
  const endpoints = [
    ['employeeId', 'employees'],
    ['contractorId', 'contractors'],
    ['payrollId', 'payrolls'],
  ] as const

  for (const [key, endpoint] of endpoints) {
    try {
      const res = await fetch(
        `${gwsFlowsHost}/fe_sdk/${flowToken}/v1/companies/${companyId}/${endpoint}`,
        { signal: AbortSignal.timeout(10000) },
      )
      if (res.ok) {
        const items = await res.json()
        if (Array.isArray(items) && items.length > 0) {
          entities[key] = items[0].uuid
        }
      }
    } catch {
      // Non-fatal
    }
  }

  return entities
}

function writeEnvFile(envPath: string, data: Record<string, string>) {
  const content = [
    `# Auto-generated by sdk-app:setup on ${new Date().toISOString()}`,
    '',
    `GWS_FLOWS_HOST=${data.gwsFlowsHost}`,
    `FLOW_TOKEN=${data.flowToken}`,
    `VITE_COMPANY_ID=${data.companyId}`,
    `VITE_EMPLOYEE_ID=${data.employeeId || ''}`,
    `VITE_CONTRACTOR_ID=${data.contractorId || ''}`,
    `VITE_PAYROLL_ID=${data.payrollId || ''}`,
    `VITE_REQUEST_ID=`,
    `VITE_DEMO_TYPE=${data.demoType}`,
    '',
  ].join('\n')

  writeFileSync(envPath, content)
}

async function main() {
  const zpEnv = process.env.npm_config_env || 'demo'
  const demoType = process.env.npm_config_demo_type || 'react_sdk_demo_company_onboarded'

  console.log(`\n  SDK Dev App Setup`)
  console.log(`  Environment: ${zpEnv}\n`)

  const actualEnv = zpEnv === 'local' ? 'localzp' : zpEnv

  const envPath = resolve(ENV_DIR, `.env.${actualEnv}`)
  const existingEnv = loadEnvFile(envPath)
  const gwsFlowsHost = existingEnv.GWS_FLOWS_HOST || ENV_DEFAULTS[actualEnv]

  if (!gwsFlowsHost) {
    console.error(`  Error: No GWS_FLOWS_HOST configured for environment "${zpEnv}"`)
    console.error(`  Known environments: demo, staging, local`)
    console.error(`  Set GWS_FLOWS_HOST in ${envPath}\n`)
    process.exit(1)
  }

  console.log(`  GWS-Flows host: ${gwsFlowsHost}`)
  console.log(`  Demo type: ${demoType}\n`)

  console.log(`  Checking connectivity...`)
  try {
    const healthRes = await fetch(`${gwsFlowsHost}/demos`, {
      signal: AbortSignal.timeout(15000),
    })
    if (!healthRes.ok && healthRes.status !== 404) {
      console.warn(`  Warning: GWS-Flows returned status ${healthRes.status}`)
    } else {
      console.log(`  GWS-Flows is reachable\n`)
    }
  } catch (err) {
    console.error(`  Error: Cannot reach ${gwsFlowsHost}`)
    console.error(`  ${err}\n`)
    process.exit(1)
  }

  const { demoId } = await createDemo(gwsFlowsHost, demoType)
  console.log(`  Demo created: ${demoId}`)

  const flowToken = await pollForFlowToken(gwsFlowsHost, demoId)
  console.log(`  Flow token: ${flowToken.slice(0, 15)}...`)

  const companyId = await fetchCompanyId(gwsFlowsHost, flowToken)
  if (companyId) {
    console.log(`  Company ID: ${companyId}`)
  } else {
    console.warn(`  Warning: Could not fetch company ID`)
  }

  let entities: Record<string, string> = {}
  if (companyId) {
    console.log(`  Fetching entity IDs...`)
    entities = await fetchEntityIds(gwsFlowsHost, flowToken, companyId)

    if (entities.employeeId) console.log(`  Employee ID: ${entities.employeeId}`)
    if (entities.contractorId) console.log(`  Contractor ID: ${entities.contractorId}`)
    if (entities.payrollId) console.log(`  Payroll ID: ${entities.payrollId}`)
  }

  writeEnvFile(envPath, {
    gwsFlowsHost,
    flowToken,
    companyId,
    demoType,
    ...entities,
  })

  console.log(`\n  Environment file written: ${envPath}`)
  console.log(`\n  Setup complete! Run: npm run sdk-app-dev --env=${zpEnv}\n`)
}

main().catch((err: unknown) => {
  console.error(`\n  Setup failed: ${String(err)}\n`)
  process.exit(1)
})
