import { existsSync, readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import type { Config } from '@docusaurus/types'
import type * as Preset from '@docusaurus/preset-classic'
import { themes as prismThemes } from 'prism-react-renderer'

// Versioning is owned by Gusto/embedded-sdk-docs, not this repo. When this
// config builds there, `versions.json` exists and lists the cut minors; when it
// builds locally on embedded-react-sdk it doesn't, and Docusaurus falls back to
// a single-version site. The same config file works in both places — no fork.
const versionsPath = resolve(__dirname, 'versions.json')

function isStringArray(val: unknown): val is string[] {
  return Array.isArray(val) && val.every(v => typeof v === 'string')
}

const rawVersions: unknown = existsSync(versionsPath)
  ? JSON.parse(readFileSync(versionsPath, 'utf8'))
  : []
if (!isStringArray(rawVersions)) {
  throw new Error('docs-site/versions.json must be a string[]')
}
const versions: string[] = rawVersions
const lastVersion = versions[0]
const hasVersions = lastVersion !== undefined

const config: Config = {
  title: 'Gusto Embedded',
  tagline: 'Embedded Payroll React SDK Documentation',
  favicon: 'img/favicon.svg',

  // This repo is the source of truth for the docs. The publish-docs.yaml
  // workflow builds this site on each NPM release and pushes the output to
  // Gusto/embedded-sdk-docs, which serves it at sdk.gusto.com. The url
  // below is what gets baked into the sitemap, canonical links, and OG
  // tags, so it must match the production domain.
  url: 'https://sdk.gusto.com',
  baseUrl: '/',

  onBrokenLinks: 'throw',
  onBrokenAnchors: 'throw',

  markdown: {
    format: 'detect',
    mermaid: true,
    hooks: {
      onBrokenMarkdownLinks: 'throw',
    },
  },

  i18n: {
    defaultLocale: 'en',
    locales: ['en'],
  },

  plugins: [
    require.resolve('./plugins/global-docs-sidebar'),
    // Emits docs-site/build/mcp/ artifacts (docs.json, search-index.json,
    // manifest.json) at build time. An MCP server adapter (Cloudflare
    // Workers, Vercel Edge, Node, etc.) wires those artifacts into a live
    // /mcp endpoint at deploy time — that piece lives in the downstream
    // hosting setup, not this repo.
    [
      'docusaurus-plugin-mcp-server',
      {
        server: {
          name: 'gusto-embedded-sdk-docs',
          version: '1.0.0',
        },
      },
    ],
  ],

  themes: [
    '@docusaurus/theme-mermaid',
    [
      require.resolve('@easyops-cn/docusaurus-search-local'),
      {
        hashed: true,
        indexBlog: false,
        docsRouteBasePath: '/docs',
        docsDir: '../docs',
        ignoreFiles: [/test-fests\//],
        searchBarShortcut: false,
        searchBarShortcutHint: false,
      },
    ],
  ],

  presets: [
    [
      'classic',
      {
        docs: {
          path: '../docs',
          routeBasePath: 'docs',
          sidebarPath: './sidebars.ts',
          breadcrumbs: true,
          exclude: ['test-fests/**'],
          // reference/index.md is the link target for the "Reference" category label.
          // Docusaurus only de-dupes category-linked docs when the category itself is
          // autogenerated (from _category_.json), not when defined manually in sidebars.ts.
          // This generator removes the duplicate child item explicitly.
          sidebarItemsGenerator: async ({ defaultSidebarItemsGenerator, ...args }) => {
            const items = await defaultSidebarItemsGenerator(args)
            return items.filter(item => !(item.type === 'doc' && item.id === 'reference/index'))
          },
          ...(hasVersions && {
            lastVersion,
            includeCurrentVersion: false,
            versions: Object.fromEntries(
              versions.map(version => [version, { banner: 'none' as const, badge: false }]),
            ),
          }),
        },
        blog: false,
        theme: {
          customCss: ['./src/css/custom.css'],
        },
      } satisfies Preset.Options,
    ],
  ],

  themeConfig: {
    // Shared styling for workflow step diagrams, applied to every Mermaid render.
    // Content/step nodes use the base theme's default neutral look (no class).
    // The accent (Gusto coral) marks control flow — branches, start/stop markers,
    // and condition edges. The only per-diagram marking is `class <node> branch`
    // on decision nodes; start/stop and edges are styled automatically below.
    // Accent colors are CSS variables defined per color mode in src/css/custom.css,
    // so the palette follows light/dark.
    mermaid: {
      // Built-in low-chroma base themes that Docusaurus swaps per color mode, so
      // everything except the accents (default nodes, event edges, labels, fonts)
      // gets coherent mode-aware defaults. Accents layer on via themeCSS below.
      theme: { light: 'neutral', dark: 'dark' },
      options: {
        // Site monospace stack (Infima default — the theme doesn't override it).
        fontFamily:
          "ui-monospace, SFMono-Regular, 'SF Mono', Menlo, Consolas, 'Liberation Mono', 'Courier New', monospace",
        // Drawing style: 'handDrawn' (sketchy), 'classic' (default), or 'neo' (modern).
        look: 'handDrawn',
        themeCSS: [
          // branch (decision) nodes — classic/neo: single filled shape; handDrawn:
          // rough.js draws two fill="none" paths (fill hatch first, border last)
          // colored via stroke, so recolor by stroke (order-coupled to rough's output).
          '.branch > rect, .branch > polygon, .branch > path { fill: var(--diagram-accent-fill); stroke: var(--diagram-accent-stroke); }',
          '.rough-node.branch > g > path:first-of-type { stroke: var(--diagram-accent-fill); }',
          '.rough-node.branch > g > path:last-of-type { stroke: var(--diagram-accent-stroke); }',
          '.branch .nodeLabel { color: var(--diagram-text); fill: var(--diagram-text); }',
          // start/stop markers (sm-circ/fr-circ) don't carry node cssClasses, so
          // target them by their stable node-id pattern. Fill + stroke so the
          // interior is the accent tint, not the gray node background showing through.
          '[id*="-flowchart-start-"] path, [id*="-flowchart-done-"] path { stroke: var(--diagram-accent-stroke); fill: var(--diagram-accent-fill); }',
          // condition edges are dotted by convention (events are solid), so the
          // built-in edge-pattern-dotted class targets them without per-diagram marking.
          '.flowchart-link.edge-pattern-dotted { stroke: var(--diagram-accent-stroke); }',
          // arrowheads are one shared marker; context-stroke makes each inherit its
          // edge's stroke, so condition arrows turn coral and event arrows stay neutral.
          '.arrowMarkerPath { fill: context-stroke; stroke: context-stroke; }',
        ].join('\n'),
      },
    },
    image: 'img/og-default.png',
    metadata: [
      {
        name: 'description',
        content:
          'Documentation for the Gusto Embedded React SDK — pre-built workflows and primitives for embedding payroll.',
      },
      {
        name: 'keywords',
        content: 'gusto, embedded payroll, react sdk, payroll api, hr api, embedded finance',
      },
      { property: 'og:type', content: 'website' },
      { property: 'og:site_name', content: 'Gusto Embedded SDK' },
      { name: 'twitter:card', content: 'summary_large_image' },
    ],
    colorMode: {
      defaultMode: 'light',
      respectPrefersColorScheme: true,
    },
    navbar: {
      logo: {
        alt: 'Gusto Embedded',
        src: 'img/gdev-logo-light.svg',
        srcDark: 'img/gdev-logo-dark.svg',
      },
      items: [
        {
          to: '/docs/',
          position: 'left',
          label: 'Docs',
        },
        {
          href: 'https://github.com/Gusto/embedded-react-sdk',
          label: 'GitHub',
          position: 'right',
          className: 'navbarGithub',
        },
      ],
    },
    footer: {
      logo: {
        alt: 'Gusto Embedded',
        src: 'img/gdev-logo-light.svg',
        srcDark: 'img/gdev-logo-dark.svg',
      },
      links: [
        {
          title: 'Build',
          items: [
            { label: 'Workflows', to: '/docs/workflows-overview' },
            { label: 'Event Handling', to: '/docs/integration-guide/event-handling' },
            { label: 'Hooks', to: '/docs/hooks' },
          ],
        },
        {
          title: 'Customize',
          items: [
            { label: 'Component Adapter', to: '/docs/component-adapter' },
            { label: 'Theming', to: '/docs/theming' },
            { label: 'Translations', to: '/docs/integration-guide/translation' },
            { label: 'Bring your own data', to: '/docs/integration-guide/providing-your-own-data' },
          ],
        },
        {
          title: 'Get Started',
          items: [
            { label: 'What is the SDK?', to: '/docs/' },
            { label: 'Getting Started', to: '/docs/getting-started' },
            { label: 'Authentication', to: '/docs/getting-started/authentication' },
          ],
        },
        {
          title: 'Resources',
          items: [
            {
              label: 'Developer Portal',
              href: 'https://docs.gusto.com/embedded-payroll/docs/introduction',
            },
            {
              label: 'GitHub',
              href: 'https://github.com/Gusto/embedded-react-sdk',
            },
            {
              label: 'Developer Terms of Service',
              href: 'https://gusto.com/legal/terms/developer-terms-of-service',
            },
          ],
        },
      ],
      copyright: `Copyright © ${new Date().getFullYear()} Gusto, Inc.`,
    },
    prism: {
      theme: prismThemes.github,
      darkTheme: prismThemes.nightOwl,
      additionalLanguages: ['bash', 'json', 'ruby', 'python', 'java'],
    },
  } satisfies Preset.ThemeConfig,
}

export default config
