import { existsSync, readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import type { Config } from '@docusaurus/types'
import type * as Preset from '@docusaurus/preset-classic'
import { themes as prismThemes } from 'prism-react-renderer'
import { CONFIG } from './src/config'

// Versioning is owned by Gusto/embedded-sdk-docs, not this repo. When this
// config builds there, `versions.json` exists and lists the cut minors; when it
// builds locally on embedded-react-sdk it doesn't, and Docusaurus falls back to
// a single-version site. The same config file works in both places — no fork.
const versionsPath = resolve(__dirname, 'versions.json')

function isStringArray(val: unknown): val is string[] {
  return Array.isArray(val) && val.every(v => typeof v === 'string')
}

const rawVersions: unknown = existsSync(versionsPath)
  ? JSON.parse(readFileSync(versionsPath, 'utf8'))
  : []
if (!isStringArray(rawVersions)) {
  throw new Error('docs-site/versions.json must be a string[]')
}
const versions: string[] = rawVersions
const lastVersion = versions[0]
const hasVersions = lastVersion !== undefined

const config: Config = {
  title: 'Gusto Embedded',
  tagline: 'Embedded Payroll React SDK Documentation',
  favicon: 'img/favicon.svg',

  // This repo is the source of truth for the docs. The publish-docs.yaml
  // workflow builds this site on each NPM release and pushes the output to
  // Gusto/embedded-sdk-docs, which serves it at sdk.gusto.com. The url
  // below is what gets baked into the sitemap, canonical links, and OG
  // tags, so it must match the production domain.
  url: 'https://sdk.gusto.com',
  baseUrl: '/',

  onBrokenLinks: 'throw',
  onBrokenAnchors: 'throw',

  markdown: {
    format: 'detect',
    mermaid: true,
    hooks: {
      onBrokenMarkdownLinks: 'throw',
    },
  },

  i18n: {
    defaultLocale: 'en',
    locales: ['en'],
  },

  plugins: [require.resolve('./plugins/global-docs-sidebar')],

  // Load the OneTrust consent platform at the application level, in <head>. OneTrust
  // is the site-wide cookie-consent gate (all categories, not just analytics), so it
  // lives here rather than inside any feature module. The domain-script variant is
  // resolved at build time (see src/analyticsConfig.ts).
  headTags: [
    {
      tagName: 'script',
      attributes: {
        src: CONFIG.ONE_TRUST.STUB_URL,
        'data-domain-script': CONFIG.ONE_TRUST.DOMAIN_SCRIPT,
      },
    },
  ],

  // cookieConsent wires the preference-center footer link and exposes the consent
  // check; gustoAnalytics loads gusto-analytics and emits page views once the OneTrust
  // consent (loaded above) is granted.
  clientModules: [
    require.resolve('./src/cookieConsent.ts'),
    require.resolve('./src/clientModules/gustoAnalytics.ts'),
  ],

  themes: [
    '@docusaurus/theme-mermaid',
    [
      require.resolve('@easyops-cn/docusaurus-search-local'),
      {
        hashed: true,
        indexBlog: false,
        docsRouteBasePath: '/docs',
        docsDir: '../docs',
        ignoreFiles: [/test-fests\//],
        searchBarShortcut: false,
        searchBarShortcutHint: false,
      },
    ],
  ],

  presets: [
    [
      'classic',
      {
        docs: {
          path: '../docs',
          routeBasePath: 'docs',
          sidebarPath: './sidebars.ts',
          breadcrumbs: true,
          exclude: ['test-fests/**'],
          // reference/index.md is the link target for the "Reference" category label.
          // Docusaurus only de-dupes category-linked docs when the category itself is
          // autogenerated (from _category_.json), not when defined manually in sidebars.ts.
          // This generator removes the duplicate child item explicitly.
          sidebarItemsGenerator: async ({ defaultSidebarItemsGenerator, ...args }) => {
            const items = await defaultSidebarItemsGenerator(args)
            return items.filter(item => !(item.type === 'doc' && item.id === 'reference/index'))
          },
          ...(hasVersions && {
            lastVersion,
            includeCurrentVersion: false,
            versions: Object.fromEntries(
              versions.map(version => [version, { banner: 'none' as const, badge: false }]),
            ),
          }),
        },
        blog: false,
        sitemap: {
          // robots.txt blocks crawlers from fetching older-minor snapshots; keep
          // them out of the sitemap too, so it advertises only the canonical,
          // unprefixed /docs/<page> (the latest minor, driven by lastVersion).
          // versions[0] is that latest minor served unprefixed, so slice(1) drops
          // just the /docs/<X.Y>/ snapshots — no maintenance as new minors land.
          ignorePatterns: hasVersions ? versions.slice(1).map(v => `/docs/${v}/**`) : [],
          changefreq: 'weekly',
          priority: 0.5,
        },
        theme: {
          customCss: ['./src/css/custom.css'],
        },
      } satisfies Preset.Options,
    ],
  ],

  themeConfig: {
    // Shared styling for workflow step diagrams, applied to every Mermaid render.
    // Content/step nodes use the base theme's default neutral look (no class).
    // The accent (Gusto coral) marks control flow — branches, start/stop markers,
    // and condition edges. The only per-diagram marking is `class <node> branch`
    // on decision nodes; start/stop and edges are styled automatically below.
    // Accent colors are CSS variables defined per color mode in src/css/custom.css,
    // so the palette follows light/dark.
    mermaid: {
      // Built-in low-chroma base themes that Docusaurus swaps per color mode, so
      // everything except the accents (default nodes, event edges, labels, fonts)
      // gets coherent mode-aware defaults. Accents layer on via themeCSS below.
      theme: { light: 'neutral', dark: 'dark' },
      options: {
        // Site monospace stack (Infima default — the theme doesn't override it).
        fontFamily:
          "ui-monospace, SFMono-Regular, 'SF Mono', Menlo, Consolas, 'Liberation Mono', 'Courier New', monospace",
        // Drawing style: 'handDrawn' (sketchy), 'classic' (default), or 'neo' (modern).
        look: 'handDrawn',
        themeCSS: [
          // branch (decision) nodes — classic/neo: single filled shape; handDrawn:
          // rough.js draws two fill="none" paths (fill hatch first, border last)
          // colored via stroke, so recolor by stroke (order-coupled to rough's output).
          '.branch > rect, .branch > polygon, .branch > path { fill: var(--diagram-accent-fill); stroke: var(--diagram-accent-stroke); }',
          '.rough-node.branch > g > path:first-of-type { stroke: var(--diagram-accent-fill); }',
          '.rough-node.branch > g > path:last-of-type { stroke: var(--diagram-accent-stroke); }',
          '.branch .nodeLabel { color: var(--diagram-text); fill: var(--diagram-text); }',
          // flow (composed-sub-flow) nodes — accent BORDER only, default fill, so a
          // node that links out to another documented flow pops without reading as a
          // branch (which fills coral). classic/neo: recolor stroke only; handDrawn:
          // recolor just the border path (last-of-type), leaving the fill hatch
          // (first-of-type) at the neutral default. Thicker stroke to emphasize.
          '.flow > rect, .flow > polygon, .flow > path { stroke: var(--diagram-accent-stroke); stroke-width: 2px; }',
          '.rough-node.flow > g > path:last-of-type { stroke: var(--diagram-accent-stroke); stroke-width: 2px; }',
          // start/stop markers (sm-circ/fr-circ) don't carry node cssClasses, so
          // target them by their stable node-id pattern. Fill + stroke so the
          // interior is the accent tint, not the gray node background showing through.
          '[id*="-flowchart-start-"] path, [id*="-flowchart-done-"] path { stroke: var(--diagram-accent-stroke); fill: var(--diagram-accent-fill); }',
          // condition edges are dotted by convention (events are solid), so the
          // built-in edge-pattern-dotted class targets them without per-diagram marking.
          '.flowchart-link.edge-pattern-dotted { stroke: var(--diagram-accent-stroke); }',
          // arrowheads are one shared marker; context-stroke makes each inherit its
          // edge's stroke, so condition arrows turn coral and event arrows stay neutral.
          '.arrowMarkerPath { fill: context-stroke; stroke: context-stroke; }',
          // subgraph clusters are pure layout-grouping, not content. handDrawn draws
          // a hatch-fill path (first-of-type) + a border path (last-of-type). Drop the
          // hatch so only the neutral border remains — a minimal box that groups nodes
          // without reading as a styled container. Titles are suppressed per-diagram via
          // empty-string subgraph labels (`[" "]`), not globally, so a real title still
          // renders if ever wanted. (classic/neo fallback: the single rect gets no fill.)
          '.cluster > g > path:first-of-type { display: none; }',
          '.cluster > rect { fill: none; }',
        ].join('\n'),
      },
    },
    image: 'img/og-default.png',
    metadata: [
      {
        name: 'description',
        content:
          'Documentation for the Gusto Embedded React SDK — pre-built workflows and primitives for embedding payroll.',
      },
      {
        name: 'keywords',
        content: 'gusto, embedded payroll, react sdk, payroll api, hr api, embedded finance',
      },
      { property: 'og:type', content: 'website' },
      { property: 'og:site_name', content: 'Gusto Embedded SDK' },
      { name: 'twitter:card', content: 'summary_large_image' },
    ],
    colorMode: {
      defaultMode: 'light',
      respectPrefersColorScheme: true,
    },
    navbar: {
      logo: {
        alt: 'Gusto Embedded',
        src: 'img/gdev-logo-light.svg',
        srcDark: 'img/gdev-logo-dark.svg',
      },
      items: [
        {
          to: '/docs/',
          position: 'left',
          label: 'Docs',
        },
        {
          href: 'https://github.com/Gusto/embedded-react-sdk',
          label: 'GitHub',
          position: 'right',
          className: 'navbarGithub',
        },
      ],
    },
    footer: {
      logo: {
        alt: 'Gusto Embedded',
        src: 'img/gdev-logo-light.svg',
        srcDark: 'img/gdev-logo-dark.svg',
      },
      links: [
        {
          title: 'Build',
          items: [
            { label: 'Workflows', to: '/docs/guides/workflows-overview' },
            { label: 'Event Handling', to: '/docs/guides/integration-guide/event-handling' },
            { label: 'Hooks', to: '/docs/reference/utilities' },
          ],
        },
        {
          title: 'Customize',
          items: [
            { label: 'Component Adapter', to: '/docs/guides/component-adapter' },
            { label: 'Theming', to: '/docs/guides/theming' },
            { label: 'Translations', to: '/docs/guides/integration-guide/translation' },
            {
              label: 'Bring your own data',
              to: '/docs/guides/integration-guide/providing-your-own-data',
            },
          ],
        },
        {
          title: 'Get Started',
          items: [
            { label: 'What is the SDK?', to: '/docs/' },
            { label: 'Getting started', to: '/docs/getting-started' },
            { label: 'Authentication', to: '/docs/getting-started/authentication' },
          ],
        },
        {
          title: 'Resources',
          items: [
            {
              label: 'Developer Portal',
              href: 'https://docs.gusto.com/embedded-payroll/docs/introduction',
            },
            {
              label: 'GitHub',
              href: 'https://github.com/Gusto/embedded-react-sdk',
            },
            {
              label: 'Developer Terms of Service',
              href: 'https://gusto.com/legal/terms/developer-terms-of-service',
            },
            {
              label: 'Privacy Notice',
              href: 'https://gusto.com/about/privacy',
            },
            {
              label: 'Cookie Settings',
              href: '#',
              // Opens the OneTrust preference center; wired up in src/gustoAnalytics.ts.
              className: 'docs-cookie-settings',
            },
          ],
        },
      ],
      copyright: `Copyright © ${new Date().getFullYear()} Gusto, Inc.`,
    },
    prism: {
      theme: {
        ...prismThemes.github,
        styles: [
          ...prismThemes.github.styles,
          {
            types: ['comment', 'prolog', 'doctype', 'cdata'],
            style: { color: '#57606a', fontStyle: 'italic' },
          },
          { types: ['string', 'attr-value'], style: { color: '#b91c5c' } },
          {
            types: [
              'entity',
              'url',
              'symbol',
              'number',
              'boolean',
              'variable',
              'constant',
              'property',
              'regex',
              'inserted',
            ],
            style: { color: '#0a7b78' },
          },
          {
            types: ['atrule', 'keyword', 'attr-name', 'selector'],
            style: { color: '#0969da' },
          },
          { types: ['function', 'deleted', 'tag'], style: { color: '#cf222e' } },
        ],
      },
      darkTheme: prismThemes.nightOwl,
      additionalLanguages: ['bash', 'json', 'ruby', 'python', 'java'],
    },
  } satisfies Preset.ThemeConfig,
}

export default config
