import type { SidebarsConfig } from '@docusaurus/plugin-content-docs'

const sidebars: SidebarsConfig = {
  docs: [
    {
      type: 'category',
      label: 'Getting Started',
      link: { type: 'doc', id: 'getting-started/getting-started' },
      collapsed: false,
      items: [
        'getting-started/quick-start',
        'getting-started/authentication',
        'getting-started/proxy-security-partner-guidance',
        'getting-started/component-types',
        'getting-started/example-app',
      ],
    },
    'workflows-overview/workflows-overview',
    {
      type: 'category',
      label: 'Component Adapter',
      link: { type: 'doc', id: 'component-adapter/component-adapter' },
      items: [
        'component-adapter/how-the-component-adapter-works',
        'component-adapter/setting-up-your-component-adapter',
        'component-adapter/component-adapter-types',
        'component-adapter/component-adapter-faq',
      ],
    },
    {
      type: 'category',
      label: 'Theming',
      link: { type: 'doc', id: 'theming/theming' },
      items: ['theming/theming-guide'],
    },
    {
      type: 'category',
      label: 'Integration Guide',
      link: { type: 'doc', id: 'integration-guide/integration-guide' },
      items: [
        'integration-guide/versioning',
        'integration-guide/event-handling',
        'integration-guide/request-interceptors',
        'integration-guide/customizing-sdk-ui',
        'integration-guide/composition',
        'integration-guide/providing-your-own-data',
        'integration-guide/translation',
        'integration-guide/routing',
        'integration-guide/error-handling',
        'integration-guide/observability',
        'integration-guide/observability-examples',
      ],
    },
    {
      type: 'category',
      label: 'Hooks',
      link: { type: 'doc', id: 'hooks/hooks' },
      items: [
        'hooks/useEmployeeDetailsForm',
        'hooks/useCompensationForm',
        'hooks/useWorkAddressForm',
      ],
    },
    {
      type: 'category',
      label: 'Reference',
      collapsible: false,
      link: { type: 'doc', id: 'reference/index' },
      items: [{ type: 'autogenerated', dirName: 'reference' }],
    },
    {
      type: 'category',
      label: 'Appendix',
      collapsed: true,
      items: [
        'appendix/endpoint-reference',
        'appendix/jobs-and-compensations',
        'appendix/proxy-examples',
      ],
    },
  ],
}

export default sidebars
