import type { SidebarsConfig } from '@docusaurus/plugin-content-docs'

const sidebars: SidebarsConfig = {
  docs: [
    {
      type: 'category',
      label: 'Getting started',
      link: { type: 'doc', id: 'getting-started/getting-started' },
      collapsed: false,
      items: [
        'getting-started/quick-start',
        'getting-started/authentication',
        'getting-started/proxy-security-partner-guidance',
        'getting-started/component-types',
        'getting-started/example-app',
      ],
    },
    {
      type: 'category',
      label: 'Guides',
      collapsed: false,
      items: [
        {
          type: 'category',
          label: 'Integration guide',
          link: { type: 'doc', id: 'guides/integration-guide/integration-guide' },
          items: [
            'guides/integration-guide/versioning',
            'guides/integration-guide/event-handling',
            'guides/integration-guide/request-interceptors',
            'guides/integration-guide/customizing-sdk-ui',
            'guides/integration-guide/composition',
            'guides/integration-guide/providing-your-own-data',
            'guides/integration-guide/translation',
            'guides/integration-guide/routing',
            'guides/integration-guide/error-handling',
            'guides/integration-guide/observability',
            'guides/integration-guide/observability-examples',
          ],
        },
        'guides/theming',
        {
          type: 'category',
          label: 'Component Adapter',
          link: { type: 'doc', id: 'guides/component-adapter/component-adapter' },
          items: [
            'guides/component-adapter/how-the-component-adapter-works',
            'guides/component-adapter/setting-up-your-component-adapter',
            'guides/component-adapter/component-adapter-types',
            'guides/component-adapter/component-adapter-faq',
          ],
        },
        'guides/workflows-overview',
        'hooks/hooks',
        'guides/proxy-examples',
        'guides/endpoint-reference',
      ],
    },
    {
      type: 'category',
      label: 'Reference',
      collapsible: false,
      link: { type: 'doc', id: 'reference/index' },
      items: [{ type: 'autogenerated', dirName: 'reference' }],
    },
  ],
}

export default sidebars
