import type { SidebarsConfig } from '@docusaurus/plugin-content-docs'

const sidebars: SidebarsConfig = {
  docs: [
    {
      type: 'category',
      label: 'Getting Started',
      link: { type: 'doc', id: 'getting-started/getting-started' },
      collapsed: false,
      items: [
        'getting-started/quick-start',
        'getting-started/authentication',
        'getting-started/proxy-security-partner-guidance',
        'getting-started/component-types',
      ],
    },
    {
      type: 'category',
      label: 'Reference',
      collapsible: false,
      items: [{ type: 'autogenerated', dirName: 'reference' }],
    },
    {
      type: 'category',
      label: 'Appendix',
      collapsed: true,
      items: [
        'appendix/endpoint-reference',
        'appendix/jobs-and-compensations',
        'appendix/proxy-examples',
      ],
    },
  ],
}

export default sidebars
