export { Dashboard } from './Dashboard'
export type { DashboardProps } from './Dashboard'
export { DashboardView } from './DashboardView'
export type { DashboardViewProps } from './DashboardView'
export { BasicDetailsView } from './BasicDetailsView'
export type { BasicDetailsViewProps } from './BasicDetailsView'
export { JobAndPayView } from './JobAndPayView'
export type { JobAndPayViewProps } from './JobAndPayView'
export { TaxesView } from './TaxesView'
export type { TaxesViewProps } from './TaxesView'
