steps:
  - name: ':docker: Build Image'
    key: docker_build
    plugins:
      - docker-compose#v4.10.1:
          image-repository: ${AWS_ECR_REPO}
          build: main
          push:
            - main:${DOCKER_IMAGE}
          cache-from:
            - main:${DOCKER_IMAGE}
            - main:${AWS_ECR_REPO}:main-ci
    timeout_in_minutes: 20
    agents:
      queue: default
    retry:
      automatic:
        - exit_status: -1 # Agent lost
          limit: 2
        - exit_status: 143 # JVM SIGTERM
          limit: 2
        - exit_status: 255 # Forced shutdown
          limit: 2
  - wait
  - group: ':lint-remover: Linting'
    key: linting
    steps:
      # Note this will only lint files from the images (only files in package folder)
      # If we want to change that behavior we will need to include ALL files in Docker image
      # All other files (at the root level) wont be linted and relies on local husky step to lint them automatically
      - label: ':eslint: ESLint'
        key: eslint
        command: 'npm run lint'
        plugins:
          - docker-compose#v4.10.1:
              run: main
        timeout_in_minutes: 10
        agents:
          queue: default
      - label: ':typescript: typecheck'
        key: typecheck
        command: 'npm run tsc'
        plugins:
          - docker-compose#v4.10.1:
              run: main
        timeout_in_minutes: 10
        agents:
          queue: default
      - label: ':prettier: Prettier'
        key: prettier
        command: 'npm run format:check'
        plugins:
          - docker-compose#v4.10.1:
              run: main
        timeout_in_minutes: 10
        agents:
          queue: default
      - label: ':stylelint: StyleLint'
        key: stylelint
        command: 'npm run stylelint'
        plugins:
          - docker-compose#v4.10.1:
              run: main
        timeout_in_minutes: 10
        agents:
          queue: default
  - group: ':test_tube: Tests'
    key: tests
    depends_on: docker_build
    steps:
      - name: ':jest: Tests'
        key: jest
        command: 'npm run test:ci'
        plugins:
          - docker-compose#v4.10.1:
              run: main
        timeout_in_minutes: 10
        agents:
          queue: default
  - wait
