import type { PayrollOption, EmployeeOption, ReversalRecord } from './types'

export const mockPayrolls: PayrollOption[] = [
  {
    uuid: 'payroll-apr-1-15-2026',
    payPeriodStart: '2026-04-01',
    payPeriodEnd: '2026-04-15',
    checkDate: '2026-04-20',
    type: 'Regular',
    employeeCount: 48,
    totalAmount: '$198,420.00',
    fundRecoveryStatus: 'eligible',
    fundRecoveryDeadline: '2026-04-26T19:00:00Z',
  },
  {
    uuid: 'payroll-mar-16-31-2026',
    payPeriodStart: '2026-03-16',
    payPeriodEnd: '2026-03-31',
    checkDate: '2026-04-05',
    type: 'Regular',
    employeeCount: 48,
    totalAmount: '$195,340.00',
    fundRecoveryStatus: 'window_closed',
  },
  {
    uuid: 'payroll-mar-1-15-2026',
    payPeriodStart: '2026-03-01',
    payPeriodEnd: '2026-03-15',
    checkDate: '2026-03-20',
    type: 'Off-cycle',
    employeeCount: 3,
    totalAmount: '$5,400.00',
    fundRecoveryStatus: 'window_closed',
  },
]

export const mockEmployees: EmployeeOption[] = [
  { uuid: 'emp-001', firstName: 'Jordan', lastName: 'Williams', department: 'Engineering', netPay: '$4,200.00' },
  { uuid: 'emp-002', firstName: 'Alex', lastName: 'Chen', department: 'Product', netPay: '$3,850.00' },
  { uuid: 'emp-003', firstName: 'Sam', lastName: 'Rivera', department: 'Design', netPay: '$3,600.00' },
  { uuid: 'emp-004', firstName: 'Morgan', lastName: 'Taylor', department: 'Sales', netPay: '$3,200.00' },
  { uuid: 'emp-005', firstName: 'Casey', lastName: 'Johnson', department: 'Engineering', netPay: '$4,100.00' },
  { uuid: 'emp-006', firstName: 'Riley', lastName: 'Martinez', department: 'Finance', netPay: '$3,750.00' },
  { uuid: 'emp-007', firstName: 'Drew', lastName: 'Thompson', department: 'Engineering', netPay: '$4,400.00' },
  { uuid: 'emp-008', firstName: 'Quinn', lastName: 'Anderson', department: 'HR', netPay: '$3,100.00' },
  { uuid: 'emp-009', firstName: 'Avery', lastName: 'Wilson', department: 'Sales', netPay: '$2,900.00' },
  { uuid: 'emp-010', firstName: 'Blake', lastName: 'Moore', department: 'Marketing', netPay: '$3,300.00' },
  { uuid: 'emp-011', firstName: 'Cameron', lastName: 'Jackson', department: 'Engineering', netPay: '$5,100.00' },
  { uuid: 'emp-012', firstName: 'Dakota', lastName: 'White', department: 'Product', netPay: '$4,050.00' },
  { uuid: 'emp-013', firstName: 'Emery', lastName: 'Harris', department: 'Design', netPay: '$3,450.00' },
  { uuid: 'emp-014', firstName: 'Finley', lastName: 'Martin', department: 'Sales', netPay: '$2,800.00' },
  { uuid: 'emp-015', firstName: 'Gray', lastName: 'Garcia', department: 'Engineering', netPay: '$4,700.00' },
  { uuid: 'emp-016', firstName: 'Harley', lastName: 'Davis', department: 'Finance', netPay: '$3,950.00' },
  { uuid: 'emp-017', firstName: 'Indigo', lastName: 'Rodriguez', department: 'Marketing', netPay: '$3,150.00' },
  { uuid: 'emp-018', firstName: 'Jamie', lastName: 'Lewis', department: 'HR', netPay: '$2,950.00' },
  { uuid: 'emp-019', firstName: 'Kendall', lastName: 'Lee', department: 'Engineering', netPay: '$5,300.00' },
  { uuid: 'emp-020', firstName: 'Lane', lastName: 'Walker', department: 'Product', netPay: '$3,700.00' },
  { uuid: 'emp-021', firstName: 'Mackenzie', lastName: 'Hall', department: 'Sales', netPay: '$3,050.00' },
  { uuid: 'emp-022', firstName: 'Morgan', lastName: 'Allen', department: 'Design', netPay: '$3,550.00' },
  { uuid: 'emp-023', firstName: 'Nico', lastName: 'Young', department: 'Engineering', netPay: '$4,850.00' },
  { uuid: 'emp-024', firstName: 'Oakley', lastName: 'Hernandez', department: 'Finance', netPay: '$4,100.00' },
  { uuid: 'emp-025', firstName: 'Parker', lastName: 'King', department: 'Marketing', netPay: '$3,250.00' },
  { uuid: 'emp-026', firstName: 'Quinn', lastName: 'Wright', department: 'HR', netPay: '$3,000.00' },
  { uuid: 'emp-027', firstName: 'Reese', lastName: 'Lopez', department: 'Engineering', netPay: '$4,600.00' },
  { uuid: 'emp-028', firstName: 'Sage', lastName: 'Hill', department: 'Product', netPay: '$3,850.00' },
  { uuid: 'emp-029', firstName: 'Tatum', lastName: 'Scott', department: 'Sales', netPay: '$2,750.00' },
  { uuid: 'emp-030', firstName: 'Urban', lastName: 'Green', department: 'Design', netPay: '$3,400.00' },
  { uuid: 'emp-031', firstName: 'Vale', lastName: 'Adams', department: 'Engineering', netPay: '$5,200.00' },
  { uuid: 'emp-032', firstName: 'West', lastName: 'Baker', department: 'Finance', netPay: '$3,800.00' },
  { uuid: 'emp-033', firstName: 'Xander', lastName: 'Gonzalez', department: 'Marketing', netPay: '$3,100.00' },
  { uuid: 'emp-034', firstName: 'Yael', lastName: 'Nelson', department: 'HR', netPay: '$2,850.00' },
  { uuid: 'emp-035', firstName: 'Zara', lastName: 'Carter', department: 'Engineering', netPay: '$4,950.00' },
  { uuid: 'emp-036', firstName: 'Ash', lastName: 'Mitchell', department: 'Product', netPay: '$3,650.00' },
  { uuid: 'emp-037', firstName: 'Billie', lastName: 'Perez', department: 'Sales', netPay: '$2,600.00' },
  { uuid: 'emp-038', firstName: 'Charlie', lastName: 'Roberts', department: 'Design', netPay: '$3,500.00' },
  { uuid: 'emp-039', firstName: 'Devon', lastName: 'Turner', department: 'Engineering', netPay: '$4,300.00' },
  { uuid: 'emp-040', firstName: 'Ellis', lastName: 'Phillips', department: 'Finance', netPay: '$3,700.00' },
  { uuid: 'emp-041', firstName: 'Fallon', lastName: 'Campbell', department: 'Marketing', netPay: '$3,050.00' },
  { uuid: 'emp-042', firstName: 'Glen', lastName: 'Parker', department: 'HR', netPay: '$2,900.00' },
  { uuid: 'emp-043', firstName: 'Haven', lastName: 'Evans', department: 'Engineering', netPay: '$5,000.00' },
  { uuid: 'emp-044', firstName: 'Ira', lastName: 'Edwards', department: 'Product', netPay: '$3,900.00' },
  { uuid: 'emp-045', firstName: 'Jules', lastName: 'Collins', department: 'Sales', netPay: '$2,750.00' },
  { uuid: 'emp-046', firstName: 'Kit', lastName: 'Stewart', department: 'Design', netPay: '$3,350.00' },
  { uuid: 'emp-047', firstName: 'Lore', lastName: 'Sanchez', department: 'Engineering', netPay: '$4,450.00' },
  { uuid: 'emp-048', firstName: 'Mace', lastName: 'Morris', department: 'Finance', netPay: '$3,600.00' },
]

export const mockReversals: ReversalRecord[] = [
  {
    reversed_payroll_uuid: 'payroll-feb-16-28-2026',
    reversal_payroll_uuid: 'reversal-payroll-0001',
    reason: 'Employee was terminated before payroll processed — pay should not have been issued.',
    approved_at: '2026-03-12T18:44:00Z',
    category: 'incorrect_payroll',
    reversed_employee_uuids: ['emp-003', 'emp-017'],
    _payPeriodLabel: 'Feb 16 – 28, 2026',
  },
  {
    reversed_payroll_uuid: 'payroll-jan-16-31-2026',
    reversal_payroll_uuid: 'reversal-payroll-0002',
    reason: 'Duplicate payroll run submitted in error.',
    approved_at: '2026-02-08T14:20:00Z',
    category: 'duplicate_payment',
    reversed_employee_uuids: ['emp-001', 'emp-002', 'emp-004', 'emp-007', 'emp-011'],
    _payPeriodLabel: 'Jan 16 – 31, 2026',
  },
  {
    reversed_payroll_uuid: 'payroll-dec-1-15-2025',
    reversal_payroll_uuid: null,
    reason: 'Employee requested reversal — direct deposit sent to closed bank account.',
    approved_at: '2026-01-03T09:15:00Z',
    category: 'convert_check_ee_requested',
    reversed_employee_uuids: ['emp-022'],
    _payPeriodLabel: 'Dec 1 – 15, 2025',
  },
]
