export { EmployeeList } from './EmployeeList/EmployeeList'
export { Deductions } from './Deductions'
export { OnboardingSummary } from './OnboardingSummary'
export { Profile } from './Profile'
export { Compensation } from './Compensation'
export { FederalTaxes } from './FederalTaxes'
export { StateTaxes } from './StateTaxes'
export { PaymentMethod } from './PaymentMethod'
export { Landing } from './Landing'
export { DocumentSigner } from './DocumentSigner'
export { OnboardingFlow } from './OnboardingFlow/OnboardingFlow'
export { SelfOnboardingFlow } from './SelfOnboardingFlow/SelfOnboardingFlow'
export { EmployeeDocuments } from './EmployeeDocuments'

export { EmploymentEligibility } from './DocumentSigner/EmploymentEligibility'
export type { EmploymentEligibilityProps } from './DocumentSigner/EmploymentEligibility'

// TODO: Remove once we have migrated partners to use the new FederalTaxes and StateTaxes components
export { Taxes } from './Taxes'

export { ExampleHomeAddress } from '@/components/UNSTABLE_Hooks/examples/ExampleHomeAddress'
export { ExampleEmployeeWorkAddress } from '@/components/UNSTABLE_Hooks/examples/ExampleEmployeeWorkAddress'
export { ExampleEmployeeDetails } from '@/components/UNSTABLE_Hooks/examples/ExampleEmployeeDetails'
export { ExampleEmployeeProfile } from '@/components/UNSTABLE_Hooks/examples/ExampleEmployeeProfile'
export { ExampleCompensation } from '@/components/UNSTABLE_Hooks/examples/ExampleCompensation'
export { ExampleStateTaxes } from '@/components/UNSTABLE_Hooks/examples/ExampleStateTaxes'
