// AUTOGENERATED by build/deriveExternalModels.ts — do not edit by hand.
// Re-exports the Gusto Embedded API entity types referenced across src so they are
// documented in the SDK reference (surfaced as the `APIModels` namespace from src/index.ts).
// Regenerate with `npm run models:derive`.

/** `Agencies` entity from the Gusto Embedded API. */
export type { Agencies } from '@gusto/embedded-api-v-2025-11-15/models/components/childsupportdata'
export type { CompanyBankAccount } from '@gusto/embedded-api-v-2025-11-15/models/components/companybankaccount'
/** `OnboardingStep` entity from the Gusto Embedded API. */
export type { OnboardingStep } from '@gusto/embedded-api-v-2025-11-15/models/components/companyonboardingstatus'
/** `MinimumWages` entity from the Gusto Embedded API. */
export type { MinimumWages } from '@gusto/embedded-api-v-2025-11-15/models/components/compensation'
export type { Compensation } from '@gusto/embedded-api-v-2025-11-15/models/components/compensation'
export { PaymentUnit } from '@gusto/embedded-api-v-2025-11-15/models/components/compensation'
export type { Contractor } from '@gusto/embedded-api-v-2025-11-15/models/components/contractor'
export {
  ContractorOnboardingStatus1,
  ContractorType,
  WageType,
} from '@gusto/embedded-api-v-2025-11-15/models/components/contractor'
/** `ContractorAddress` entity from the Gusto Embedded API. */
export type { ContractorAddress } from '@gusto/embedded-api-v-2025-11-15/models/components/contractoraddress'
/** `ContractorBankAccount` entity from the Gusto Embedded API. */
export type { ContractorBankAccount } from '@gusto/embedded-api-v-2025-11-15/models/components/contractorbankaccount'
export type { ContractorCreateRequestBody } from '@gusto/embedded-api-v-2025-11-15/models/components/contractorcreaterequestbody'
export type { ContractorPaymentForGroup } from '@gusto/embedded-api-v-2025-11-15/models/components/contractorpaymentforgroup'
export type { ContractorPaymentForGroupPreview } from '@gusto/embedded-api-v-2025-11-15/models/components/contractorpaymentforgrouppreview'
export type { ContractorPaymentGroup } from '@gusto/embedded-api-v-2025-11-15/models/components/contractorpaymentgroup'
export type { ContractorPaymentGroupPreview } from '@gusto/embedded-api-v-2025-11-15/models/components/contractorpaymentgrouppreview'
export type { ContractorPaymentGroupWithBlockers } from '@gusto/embedded-api-v-2025-11-15/models/components/contractorpaymentgroupwithblockers'
/** `ContractorPaymentReceipt` entity from the Gusto Embedded API. */
export type { ContractorPaymentReceipt } from '@gusto/embedded-api-v-2025-11-15/models/components/contractorpaymentreceipt'
export type { ContractorUpdateRequestBody } from '@gusto/embedded-api-v-2025-11-15/models/components/contractorupdaterequestbody'
/** `Document` entity from the Gusto Embedded API. */
export type { Document } from '@gusto/embedded-api-v-2025-11-15/models/components/document'
export type { Employee } from '@gusto/embedded-api-v-2025-11-15/models/components/employee'
/** `EmployeeAddress` entity from the Gusto Embedded API. */
export type { EmployeeAddress } from '@gusto/embedded-api-v-2025-11-15/models/components/employeeaddress'
/** `EmployeeBankAccount` entity from the Gusto Embedded API. */
export type { EmployeeBankAccount } from '@gusto/embedded-api-v-2025-11-15/models/components/employeebankaccount'
export type { EmployeeFederalTax } from '@gusto/embedded-api-v-2025-11-15/models/components/employeefederaltax'
export type { EmployeeFederalTaxRev2020 } from '@gusto/embedded-api-v-2025-11-15/models/components/employeefederaltaxrev2020'
export type { EmployeeOnboardingStatus } from '@gusto/embedded-api-v-2025-11-15/models/components/employeeonboardingstatus'
/** `EmployeePaymentMethod` entity from the Gusto Embedded API. */
export type { EmployeePaymentMethod } from '@gusto/embedded-api-v-2025-11-15/models/components/employeepaymentmethod'
/** `EmployeeStateTaxesList` entity from the Gusto Embedded API. */
export type { EmployeeStateTaxesList } from '@gusto/embedded-api-v-2025-11-15/models/components/employeestatetaxeslist'
/** `EmployeeStateTaxesRequest` entity from the Gusto Embedded API. */
export type { EmployeeStateTaxesRequest } from '@gusto/embedded-api-v-2025-11-15/models/components/employeestatetaxesrequest'
/** `States` entity from the Gusto Embedded API. */
export type { States } from '@gusto/embedded-api-v-2025-11-15/models/components/employeestatetaxesrequest'
/** `EmployeeStateTaxQuestion` entity from the Gusto Embedded API. */
export type { EmployeeStateTaxQuestion } from '@gusto/embedded-api-v-2025-11-15/models/components/employeestatetaxquestion'
/** `EmployeeWorkAddress` entity from the Gusto Embedded API. */
export type { EmployeeWorkAddress } from '@gusto/embedded-api-v-2025-11-15/models/components/employeeworkaddress'
/** `EntityErrorObject` entity from the Gusto Embedded API. */
export type { EntityErrorObject } from '@gusto/embedded-api-v-2025-11-15/models/components/entityerrorobject'
/** `FederalTaxDetails` entity from the Gusto Embedded API. */
export type { FederalTaxDetails } from '@gusto/embedded-api-v-2025-11-15/models/components/federaltaxdetails'
/** `TaxPayerType` entity from the Gusto Embedded API. */
export { TaxPayerType } from '@gusto/embedded-api-v-2025-11-15/models/components/federaltaxdetails'
export { FilingForm } from '@gusto/embedded-api-v-2025-11-15/models/components/federaltaxdetails'
export { FlsaStatusType } from '@gusto/embedded-api-v-2025-11-15/models/components/flsastatustype'
/** `Form` entity from the Gusto Embedded API. */
export type { Form } from '@gusto/embedded-api-v-2025-11-15/models/components/form'
/** `GarnishmentType` entity from the Gusto Embedded API. */
export { GarnishmentType } from '@gusto/embedded-api-v-2025-11-15/models/components/garnishment'
export type { Garnishment } from '@gusto/embedded-api-v-2025-11-15/models/components/garnishment'
export { PaymentPeriod } from '@gusto/embedded-api-v-2025-11-15/models/components/garnishmentchildsupport'
export type { HolidayPayPolicy } from '@gusto/embedded-api-v-2025-11-15/models/components/holidaypaypolicy'
/** `DocumentType` entity from the Gusto Embedded API. */
export { DocumentType } from '@gusto/embedded-api-v-2025-11-15/models/components/i9authorization'
export { AuthorizationStatus } from '@gusto/embedded-api-v-2025-11-15/models/components/i9authorization'
/** `RequiredQuestions` entity from the Gusto Embedded API. */
export type { RequiredQuestions } from '@gusto/embedded-api-v-2025-11-15/models/components/informationrequest'
export type { InformationRequest } from '@gusto/embedded-api-v-2025-11-15/models/components/informationrequest'
export {
  InformationRequestStatus,
  InformationRequestType,
  ResponseType,
} from '@gusto/embedded-api-v-2025-11-15/models/components/informationrequest'
export type { Job } from '@gusto/embedded-api-v-2025-11-15/models/components/job'
export type { Location } from '@gusto/embedded-api-v-2025-11-15/models/components/location'
export type { MinimumWage } from '@gusto/embedded-api-v-2025-11-15/models/components/minimumwage'
export type { PaidTimeOff } from '@gusto/embedded-api-v-2025-11-15/models/components/paidtimeoff'
export { PaymentSpeed } from '@gusto/embedded-api-v-2025-11-15/models/components/paymentconfigs'
export type { PaymentMethodBankAccount } from '@gusto/embedded-api-v-2025-11-15/models/components/paymentmethodbankaccount'
export type { PayPeriod } from '@gusto/embedded-api-v-2025-11-15/models/components/payperiod'
/** `EmployeeCompensations` entity from the Gusto Embedded API. */
export type { EmployeeCompensations } from '@gusto/embedded-api-v-2025-11-15/models/components/payroll'
/** `OffCycleReasonType` entity from the Gusto Embedded API. */
export { OffCycleReasonType } from '@gusto/embedded-api-v-2025-11-15/models/components/payroll'
/** `Payroll` entity from the Gusto Embedded API. */
export type { Payroll } from '@gusto/embedded-api-v-2025-11-15/models/components/payroll'
/** `PayrollShow` entity from the Gusto Embedded API. */
export type { PayrollShow } from '@gusto/embedded-api-v-2025-11-15/models/components/payroll'
/** `PayrollShowFixedCompensations` entity from the Gusto Embedded API. */
export type { PayrollShowFixedCompensations } from '@gusto/embedded-api-v-2025-11-15/models/components/payroll'
export type { PayrollPrepared } from '@gusto/embedded-api-v-2025-11-15/models/components/payroll'
/** `PayrollCreditBlockerTypeUnblockOptions` entity from the Gusto Embedded API. */
export type { PayrollCreditBlockerTypeUnblockOptions } from '@gusto/embedded-api-v-2025-11-15/models/components/payrollcreditblockertype'
export type { PayrollCreditBlockerType } from '@gusto/embedded-api-v-2025-11-15/models/components/payrollcreditblockertype'
/** `PayrollEmployeeCompensationsType` entity from the Gusto Embedded API. */
export type { PayrollEmployeeCompensationsType } from '@gusto/embedded-api-v-2025-11-15/models/components/payrollemployeecompensationstype'
/** `PayrollEmployeeCompensationsTypeFixedCompensations` entity from the Gusto Embedded API. */
export type { PayrollEmployeeCompensationsTypeFixedCompensations } from '@gusto/embedded-api-v-2025-11-15/models/components/payrollemployeecompensationstype'
/** `PayrollEmployeeCompensationsTypePaidTimeOff` entity from the Gusto Embedded API. */
export type { PayrollEmployeeCompensationsTypePaidTimeOff } from '@gusto/embedded-api-v-2025-11-15/models/components/payrollemployeecompensationstype'
/** `PayrollEmployeeCompensationsTypeReimbursements` entity from the Gusto Embedded API. */
export type { PayrollEmployeeCompensationsTypeReimbursements } from '@gusto/embedded-api-v-2025-11-15/models/components/payrollemployeecompensationstype'
export { PayrollEmployeeCompensationsTypePaymentMethod } from '@gusto/embedded-api-v-2025-11-15/models/components/payrollemployeecompensationstype'
/** `PayrollFixedCompensationTypesType` entity from the Gusto Embedded API. */
export type { PayrollFixedCompensationTypesType } from '@gusto/embedded-api-v-2025-11-15/models/components/payrollfixedcompensationtypestype'
/** `PayrollPayPeriodType` entity from the Gusto Embedded API. */
export type { PayrollPayPeriodType } from '@gusto/embedded-api-v-2025-11-15/models/components/payrollpayperiodtype'
/** `PayrollProcessingRequest` entity from the Gusto Embedded API. */
export type { PayrollProcessingRequest } from '@gusto/embedded-api-v-2025-11-15/models/components/payrollprocessingrequest'
export { PayrollProcessingRequestStatus } from '@gusto/embedded-api-v-2025-11-15/models/components/payrollprocessingrequest'
/** `PayrollReceipt` entity from the Gusto Embedded API. */
export type { PayrollReceipt } from '@gusto/embedded-api-v-2025-11-15/models/components/payrollreceipt'
/** `PayrollReceiptEmployeeCompensations` entity from the Gusto Embedded API. */
export type { PayrollReceiptEmployeeCompensations } from '@gusto/embedded-api-v-2025-11-15/models/components/payrollreceipt'
/** `Taxes` entity from the Gusto Embedded API. */
export type { Taxes } from '@gusto/embedded-api-v-2025-11-15/models/components/payrollreceipt'
/** `UnblockOptions` entity from the Gusto Embedded API. */
export type { UnblockOptions } from '@gusto/embedded-api-v-2025-11-15/models/components/payrollsubmissionblockertype'
export type { PayrollSubmissionBlockerType } from '@gusto/embedded-api-v-2025-11-15/models/components/payrollsubmissionblockertype'
/** `PayrollUpdateEmployeeCompensations` entity from the Gusto Embedded API. */
export type { PayrollUpdateEmployeeCompensations } from '@gusto/embedded-api-v-2025-11-15/models/components/payrollupdate'
/** `PayrollUpdateReimbursements` entity from the Gusto Embedded API. */
export type { PayrollUpdateReimbursements } from '@gusto/embedded-api-v-2025-11-15/models/components/payrollupdate'
export type { PaySchedulePreviewPayPeriod } from '@gusto/embedded-api-v-2025-11-15/models/components/payschedulepreviewpayperiod'
export type { PayScheduleShow } from '@gusto/embedded-api-v-2025-11-15/models/components/payscheduleshow'
export type { RecoveryCase } from '@gusto/embedded-api-v-2025-11-15/models/components/recoverycase'
export { RecoveryCaseStatus } from '@gusto/embedded-api-v-2025-11-15/models/components/recoverycase'
export type { Signatory } from '@gusto/embedded-api-v-2025-11-15/models/components/signatory'
/** `TaxRequirement` entity from the Gusto Embedded API. */
export type { TaxRequirement } from '@gusto/embedded-api-v-2025-11-15/models/components/taxrequirement'
/** `TaxRequirementsState` entity from the Gusto Embedded API. */
export type { TaxRequirementsState } from '@gusto/embedded-api-v-2025-11-15/models/components/taxrequirementsstate'
/** `TaxRequirementStatesList` entity from the Gusto Embedded API. */
export type { TaxRequirementStatesList } from '@gusto/embedded-api-v-2025-11-15/models/components/taxrequirementstateslist'
export { SetupStatus } from '@gusto/embedded-api-v-2025-11-15/models/components/taxrequirementstateslist'
export type { Termination } from '@gusto/embedded-api-v-2025-11-15/models/components/termination'
export type { TimeOffPolicy } from '@gusto/embedded-api-v-2025-11-15/models/components/timeoffpolicy'
export { PolicyType } from '@gusto/embedded-api-v-2025-11-15/models/components/timeoffpolicy'
export type { TimeOffPolicyRequest } from '@gusto/embedded-api-v-2025-11-15/models/components/timeoffpolicyrequest'
export type { UnprocessedTerminationPayPeriod } from '@gusto/embedded-api-v-2025-11-15/models/components/unprocessedterminationpayperiod'
export type { WireInRequest } from '@gusto/embedded-api-v-2025-11-15/models/components/wireinrequest'
export { WireInRequestStatus } from '@gusto/embedded-api-v-2025-11-15/models/components/wireinrequest'
