import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebar: SidebarsConfig = {
  apisidebar: [
    {
      type: "doc",
      id: "api/gusto-api",
    },
    {
      type: "category",
      label: "Introspection",
      link: {
        type: "doc",
        id: "api/introspection",
      },
      items: [
        {
          type: "doc",
          id: "api/get-v-1-token-info",
          label: "Get info about the current access token",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/oauth-access-token",
          label: "Create a System Access Token or Refresh an Access Token",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Companies",
      link: {
        type: "doc",
        id: "api/companies",
      },
      items: [
        {
          type: "doc",
          id: "api/schemas/company",
          label: "Company",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/company-onboarding-status",
          label: "Company-Onboarding-Status",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/post-v-1-partner-managed-companies",
          label: "Create a partner managed company",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-v-1-companies",
          label: "Get a company",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/put-v-1-companies",
          label: "Update a company",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/put-v-1-partner-managed-companies-company-uuid-migrate",
          label: "Migrate company to embedded payroll",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/get-v-1-partner-managed-companies-company-uuid-migration-readiness",
          label: "Check company migration readiness",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/post-partner-managed-companies-company-uuid-accept-terms-of-service",
          label: "Accept terms of service for a company user",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/post-partner-managed-companies-company-uuid-retrieve-terms-of-service",
          label: "Retrieve terms of service status for a company user",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/post-v-1-companies-company-id-admins",
          label: "Create an admin for the company",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-v-1-companies-company-id-admins",
          label: "Get all the admins at a company",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/get-v-1-company-onboarding-status",
          label: "Get company onboarding status",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/get-v-1-company-finish-onboarding",
          label: "Finish company onboarding",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/get-v-1-companies-company-id-custom-fields",
          label: "Get the custom fields of a company",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/get-companies-company-uuid-suspensions",
          label: "Get suspensions for this company",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/post-companies-company-uuid-suspensions",
          label: "Suspend a company's account",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Flows",
      link: {
        type: "doc",
        id: "api/flows",
      },
      items: [
        {
          type: "doc",
          id: "api/schemas/flow",
          label: "Flow",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/post-v-1-company-flows",
          label: "Create a flow",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Locations",
      link: {
        type: "doc",
        id: "api/locations",
      },
      items: [
        {
          type: "doc",
          id: "api/post-v-1-companies-company-id-locations",
          label: "Create a company location",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-v-1-companies-company-id-locations",
          label: "Get all company locations",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/get-v-1-locations-location-id",
          label: "Get a location",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/put-v-1-locations-location-id",
          label: "Update a location",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/get-v-1-locations-location-uuid-minimum-wages",
          label: "Get minimum wages for a location",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Bank Accounts",
      link: {
        type: "doc",
        id: "api/bank-accounts",
      },
      items: [
        {
          type: "doc",
          id: "api/get-v-1-companies-company-id-bank-accounts",
          label: "Get all company bank accounts",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/post-v-1-companies-company-id-bank-accounts",
          label: "Create a company bank account",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/put-v-1-companies-company-id-bank-accounts-verify",
          label: "Verify a company bank account",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/post-v-1-plaid-processor-token",
          label: "Create a bank account from a plaid processor token",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/delete-v-1-companies-company-id-bank-accounts-bank-account-id",
          label: "Delete a company bank account",
          className: "api-method delete",
        },
      ],
    },
    {
      type: "category",
      label: "Payment Configs",
      link: {
        type: "doc",
        id: "api/payment-configs",
      },
      items: [
        {
          type: "doc",
          id: "api/schemas/payment-configs",
          label: "Payment-Configs",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/get-v-1-company-payment-configs",
          label: "Get a company's payment configs",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/put-v-1-company-payment-configs",
          label: "Update a company's payment configs",
          className: "api-method put",
        },
      ],
    },
    {
      type: "category",
      label: "Pay Schedules",
      link: {
        type: "doc",
        id: "api/pay-schedules",
      },
      items: [
        {
          type: "doc",
          id: "api/schemas/pay-schedule",
          label: "Pay Schedule",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/pay-schedule",
          label: "Pay Schedule",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/pay-schedule-assignment",
          label: "Pay-Schedule-Assignment",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/pay-schedule-assignment-employee",
          label: "Pay-Schedule-Assignment-Employee",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/pay-schedule-assignment-department",
          label: "Pay-Schedule-Assignment-Department",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/pay-schedule-assignment-preview",
          label: "Pay-Schedule-Assignment-Preview",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/pay-schedule-assignment-employee-change",
          label: "Pay-Schedule-Assignment-Employee-Change",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/pay-schedule-assignment-pay-period",
          label: "Pay-Schedule-Assignment-Pay-Period",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/pay-schedule-assignment-transition-pay-period",
          label: "Pay-Schedule-Assignment-Transition-Pay-Period",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/post-v-1-companies-company-id-pay-schedules",
          label: "Create a new pay schedule",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-v-1-companies-company-id-pay-schedules",
          label: "Get the pay schedules for a company",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/get-v-1-companies-company-id-pay-schedules-preview",
          label: "Preview pay schedule dates",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/get-v-1-companies-company-id-pay-schedules-pay-schedule-id",
          label: "Get a pay schedule",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/put-v-1-companies-company-id-pay-schedules-pay-schedule-id",
          label: "Update a pay schedule",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/get-v-1-companies-company-id-unprocessed-termination-pay-periods",
          label: "Get termination pay periods for a company",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/get-v-1-companies-company-id-pay-schedules-assignments",
          label: "Get pay schedule assignments for a company",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/post-v-1-companies-company-id-pay-schedules-assignment-preview",
          label: "Preview pay schedule assignments for a company",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/post-v-1-companies-company-id-pay-schedules-assign",
          label: "Assign pay schedules for a company",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Employees",
      link: {
        type: "doc",
        id: "api/employees",
      },
      items: [
        {
          type: "doc",
          id: "api/get-v-1-companies-company-id-employees",
          label: "Get employees of a company",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/post-v-1-employees",
          label: "Create an employee",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-v-1-companies-company-id-employees-payment-details",
          label: "Get employee payment details for a company",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/post-v-1-historical-employees",
          label: "Create a historical employee",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/put-v-1-historical-employees",
          label: "Update a historical employee",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/get-v-1-employees",
          label: "Get an employee",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/put-v-1-employees",
          label: "Update an employee.",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/delete-v-1-employee",
          label: "Delete an onboarding employee",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/get-v-1-employees-employee-id-custom-fields",
          label: "Get an employee's custom fields",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/put-v-1-employees-employee-id-onboarding-documents-config",
          label: "Update employee onboarding documents config",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/get-v-1-employees-employee-id-onboarding-status",
          label: "Get the employee's onboarding status",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/put-v-1-employees-employee-id-onboarding-status",
          label: "Update the employee's onboarding status",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/get-version-employees-time-off-activities",
          label: "Get employee time off activities",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Employee Tax Setup",
      link: {
        type: "doc",
        id: "api/employee-tax-setup",
      },
      items: [
        {
          type: "doc",
          id: "api/schemas/employee-federal-tax",
          label: "Employee-Federal-Tax",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/employee-state-tax",
          label: "Employee-State-Tax",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/employee-federal-tax-pre-2020",
          label: "Employee-Federal-Tax-Pre2020",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/employee-federal-tax-rev-2020",
          label: "Employee-Federal-Tax-Rev2020",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/get-v-1-employees-employee-id-federal-taxes",
          label: "Get federal taxes for an employee",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/put-v-1-employees-employee-id-federal-taxes",
          label: "Update federal taxes for an employee",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/get-v-1-employees-employee-id-state-taxes",
          label: "Get an employee's state taxes",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/put-v-1-employees-employee-id-state-taxes",
          label: "Update an employee's state taxes",
          className: "api-method put",
        },
      ],
    },
    {
      type: "category",
      label: "Employee Payment Method",
      link: {
        type: "doc",
        id: "api/employee-payment-method",
      },
      items: [
        {
          type: "doc",
          id: "api/schemas/employee-bank-account",
          label: "Employee-Bank-Account",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/employee-payment-method",
          label: "Employee-Payment-Method",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/post-v-1-employees-employee-id-bank-accounts",
          label: "Create an employee bank account",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-v-1-employees-employee-id-bank-accounts",
          label: "Get all employee bank accounts",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/delete-v-1-employees-employee-id-bank-accounts-bank-account-id",
          label: "Delete an employee bank account",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/put-v-1-employees-employee-id-bank-accounts",
          label: "Update an employee bank account",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/get-v-1-employees-employee-id-payment-method",
          label: "Get payment method for an employee",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/put-v-1-employees-employee-id-payment-method",
          label: "Update payment method for an employee",
          className: "api-method put",
        },
      ],
    },
    {
      type: "category",
      label: "Employee Employments",
      link: {
        type: "doc",
        id: "api/employee-employments",
      },
      items: [
        {
          type: "doc",
          id: "api/schemas/unprocessed-termination-pay-period",
          label: "Unprocessed-Termination-Pay-Period",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/post-v-1-employees-employee-id-terminations",
          label: "Create an employee termination",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-v-1-employees-employee-id-terminations",
          label: "Get terminations for an employee",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/delete-v-1-employees-employee-id-terminations",
          label: "Delete an employee termination",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/put-v-1-terminations-employee-id",
          label: "Update an employee termination",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/post-v-1-employees-employee-id-rehire",
          label: "Create an employee rehire",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/put-v-1-employees-employee-id-rehire",
          label: "Update an employee rehire",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/get-v-1-employees-employee-id-rehire",
          label: "Get an employee rehire",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/delete-v-1-employees-employee-id-rehire",
          label: "Delete an employee rehire",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/get-v-1-employees-employee-id-employment-history",
          label: "Get employment history for an employee",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Employee Addresses",
      link: {
        type: "doc",
        id: "api/employee-addresses",
      },
      items: [
        {
          type: "doc",
          id: "api/get-v-1-employees-employee-id-home-addresses",
          label: "Get an employee's home addresses",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/post-v-1-employees-employee-id-home-addresses",
          label: "Create an employee's home address",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-v-1-home-addresses-home-address-uuid",
          label: "Get an employee's home address",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/put-v-1-home-addresses-home-address-uuid",
          label: "Update an employee's home address",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/delete-v-1-home-addresses-home-address-uuid",
          label: "Delete an employee's home address",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/get-v-1-employees-employee-id-work-addresses",
          label: "Get an employee's work addresses",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/post-v-1-employees-employee-id-work-addresses",
          label: "Create an employee work address",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-v-1-work-addresses-work-address-uuid",
          label: "Get an employee work address",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/put-v-1-work-addresses-work-address-uuid",
          label: "Update an employee work address",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/delete-v-1-work-addresses-work-address-uuid",
          label: "Delete an employee's work address",
          className: "api-method delete",
        },
      ],
    },
    {
      type: "category",
      label: "Jobs and Compensations",
      link: {
        type: "doc",
        id: "api/jobs-and-compensations",
      },
      items: [
        {
          type: "doc",
          id: "api/post-v-1-jobs-job-id",
          label: "Create a job",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-v-1-employees-employee-id-jobs",
          label: "Get jobs for an employee",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/get-v-1-jobs-job-id",
          label: "Get a job",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/put-v-1-jobs-job-id",
          label: "Update a job",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/delete-v-1-jobs-job-id",
          label: "Delete an individual job",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/get-v-1-jobs-job-id-compensations",
          label: "Get compensations for a job",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/post-v-1-compensations-compensation-id",
          label: "Create a compensation",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-v-1-compensations-compensation-id",
          label: "Get a compensation",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/put-v-1-compensations-compensation-id",
          label: "Update a compensation",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/delete-v-1-compensations-compensation-id",
          label: "Delete a compensation",
          className: "api-method delete",
        },
      ],
    },
    {
      type: "category",
      label: "Earning Types",
      link: {
        type: "doc",
        id: "api/earning-types",
      },
      items: [
        {
          type: "doc",
          id: "api/schemas/earning-type",
          label: "Earning-Type",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/post-v-1-companies-company-id-earning-types",
          label: "Create a custom earning type",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-v-1-companies-company-id-earning-types",
          label: "Get all earning types for a company",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/put-v-1-companies-company-id-earning-types-earning-type-uuid",
          label: "Update an earning type",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/delete-v-1-companies-company-id-earning-types-earning-type-uuid",
          label: "Deactivate an earning type",
          className: "api-method delete",
        },
      ],
    },
    {
      type: "category",
      label: "I-9 Verification",
      link: {
        type: "doc",
        id: "api/i-9-verification",
      },
      items: [
        {
          type: "doc",
          id: "api/schemas/i-9-authorization",
          label: "I9-Authorization",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/i-9-authorization-document",
          label: "I9-Authorization-Document",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/i-9-authorization-document-option",
          label: "I9-Authorization-Document-Option",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/get-v-1-employees-employee-id-i-9-authorization",
          label: "Get an employee's I-9 authorization",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/put-v-1-employees-employee-id-i-9-authorization",
          label: "Create or update an employee's I-9 authorization",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/get-v-1-employees-employee-id-i-9-authorization-document-options",
          label: "Get an employee's I-9 verification document options",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/get-v-1-employees-employee-id-i-9-authorization-documents",
          label: "Get an employee's I-9 verification documents",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/put-v-1-employees-employee-id-i-9-authorization-documents",
          label: "Create an employee's I-9 authorization verification documents",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/delete-v-1-employees-employee-id-i-9-authorization-documents-document-id",
          label: "Delete an employee's I-9 verification document",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/put-v-1-employees-employee-id-i-9-authorization-employer-sign",
          label: "Employer sign an employee's Form I-9",
          className: "api-method put",
        },
      ],
    },
    {
      type: "category",
      label: "Contractor Payment Groups",
      link: {
        type: "doc",
        id: "api/contractor-payment-groups",
      },
      items: [
        {
          type: "doc",
          id: "api/schemas/contractor-payment-group",
          label: "Contractor-Payment-Group",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/contractor-payment-group-minimal",
          label: "Contractor-Payment-Group-Minimal",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/contractor-payment-for-group",
          label: "Contractor-Payment-For-Group",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/contractor-payment-for-group-preview",
          label: "Contractor-Payment-For-Group-Preview",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/contractor-payment-group-with-blockers",
          label: "Contractor-Payment-Group-With-Blockers",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/get-v-1-companies-company-id-contractor-payment-groups",
          label: "Get contractor payment groups for a company",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/post-v-1-companies-company-id-contractor-payment-groups",
          label: "Create a contractor payment group",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/post-v-1-companies-company-id-contractor-payment-groups-preview",
          label: "Preview a contractor payment group",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-v-1-contractor-payment-groups-contractor-payment-group-id",
          label: "Get a contractor payment group",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/delete-v-1-contractor-payment-groups-contractor-payment-group-id",
          label: "Cancel a contractor payment group",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/put-v-1-contractor-payment-groups-contractor-payment-group-id-fund",
          label: "Fund a contractor payment group [DEMO]",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/get-v-1-contractor-payment-groups-id-partner-disbursements",
          label: "Get partner disbursements for a contractor payment group",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/patch-v-1-contractor-payment-groups-id-partner-disbursements",
          label: "Update partner disbursements for a contractor payment group",
          className: "api-method patch",
        },
      ],
    },
    {
      type: "category",
      label: "Contractor Payment Method",
      link: {
        type: "doc",
        id: "api/contractor-payment-method",
      },
      items: [
        {
          type: "doc",
          id: "api/schemas/contractor-payment-method",
          label: "Contractor-Payment-Method",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/contractor-bank-account",
          label: "Contractor-Bank-Account",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/post-v-1-contractors-contractor-uuid-bank-accounts",
          label: "Create a contractor bank account",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-v-1-contractors-contractor-uuid-bank-accounts",
          label: "Get all contractor bank accounts",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/get-v-1-contractors-contractor-uuid-payment-method",
          label: "Get a contractor's payment method",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/put-v-1-contractors-contractor-id-payment-method",
          label: "Update a contractor's payment method",
          className: "api-method put",
        },
      ],
    },
    {
      type: "category",
      label: "Contractor Payments",
      link: {
        type: "doc",
        id: "api/contractor-payments",
      },
      items: [
        {
          type: "doc",
          id: "api/schemas/contractor-payment",
          label: "Contractor Payment",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/contractor-payment-summary",
          label: "Contractor-Payment-Summary",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/contractor-payment-summary-by-dates",
          label: "Contractor-Payment-Summary-By-Dates",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/contractor-payment-body",
          label: "Contractor-Payment-Body",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/get-v-1-contractor-payments-contractor-payment-uuid-receipt",
          label: "Get a single contractor payment receipt",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/get-v-1-contractor-payments-contractor-payment-uuid-fund",
          label: "Fund a contractor payment [DEMO]",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/post-v-1-companies-company-id-contractor-payments",
          label: "Create a contractor payment",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-v-1-companies-company-id-contractor-payments",
          label: "Get contractor payments for a company",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/get-v-1-companies-company-id-contractor-payment-contractor-payment",
          label: "Get a single contractor payment",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/delete-v-1-companies-company-id-contractor-payment-contractor-payment",
          label: "Cancel a contractor payment",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/get-companies-company-uuid-contractor-payments-preview",
          label: "Preview contractor payment debit date",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Contractors",
      link: {
        type: "doc",
        id: "api/contractors",
      },
      items: [
        {
          type: "doc",
          id: "api/schemas/contractor",
          label: "Contractor",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/post-v-1-companies-company-uuid-contractors",
          label: "Create a contractor",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-v-1-companies-company-uuid-contractors",
          label: "Get contractors of a company",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/get-v-1-contractors-contractor-uuid",
          label: "Get a contractor",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/put-v-1-contractors-contractor-uuid",
          label: "Update a contractor",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/delete-v-1-contractors-contractor-uuid",
          label: "Delete a contractor",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/get-v-1-contractors-contractor-uuid-onboarding-status",
          label: "Get the contractor's onboarding status",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/put-v-1-contractors-contractor-uuid-onboarding-status",
          label: "Change the contractor's onboarding status",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/get-v-1-contractors-contractor-uuid-address",
          label: "Get a contractor address",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/put-v-1-contractors-contractor-uuid-address",
          label: "Create or update a contractor's address",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/get-v-1-companies-company-id-contractors-payment-details",
          label: "List contractor payment details",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Payrolls",
      link: {
        type: "doc",
        id: "api/payrolls",
      },
      items: [
        {
          type: "doc",
          id: "api/schemas/employee-pay-stub",
          label: "Employee-Pay-Stub",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/pay-period",
          label: "Pay-Period",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/payroll-minimal",
          label: "Payroll-Minimal",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/get-v-1-companies-company-id-pay-periods",
          label: "Get pay periods for a company",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/get-v-1-companies-company-id-payrolls",
          label: "Get all payrolls for a company",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/post-v-1-companies-company-id-payrolls",
          label: "Create an off-cycle payroll",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-v-1-companies-company-id-payroll-reversals",
          label: "Get approved payroll reversals",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/get-v-1-companies-company-id-payrolls-payroll-id",
          label: "Get a single payroll",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/put-v-1-companies-company-id-payrolls",
          label: "Update a payroll by ID",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/delete-v-1-companies-company-id-payrolls",
          label: "Delete a payroll",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/put-v-1-companies-company-id-payrolls-payroll-id-prepare",
          label: "Prepare a payroll for update",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/get-v-1-payment-receipts-payrolls-payroll-uuid",
          label: "Get a single payroll receipt",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/get-v-1-companies-payroll-blockers-company-uuid",
          label: "Get all payroll blockers for a company",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/post-companies-payroll-skip-company-uuid",
          label: "Skip a payroll",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/post-payrolls-gross-up-payroll-uuid",
          label: "Calculate gross up for a payroll",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/put-v-1-companies-company-id-payrolls-payroll-id-calculate",
          label: "Calculate a payroll",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/put-v-1-companies-company-id-payrolls-payroll-id-submit",
          label: "Submit payroll",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/put-api-v-1-companies-company-id-payrolls-payroll-id-cancel",
          label: "Cancel a payroll",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/get-v-1-payrolls-payroll-uuid-employees-employee-uuid-pay-stub",
          label: "Get an employee pay stub (pdf)",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/get-v-1-employees-employee-uuid-pay-stubs",
          label: "Get an employee's pay stubs",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/post-v-1-payrolls-payroll-uuid-generated-documents-printable-payroll-checks",
          label: "Generate printable payroll checks (pdf)",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-v-1-companies-company-id-payrolls-id-partner-disbursements",
          label: "Get partner disbursements for a payroll",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/patch-v-1-companies-company-id-payrolls-id-partner-disbursements",
          label: "Update partner disbursements for a payroll",
          className: "api-method patch",
        },
      ],
    },
    {
      type: "category",
      label: "Company Forms",
      link: {
        type: "doc",
        id: "api/company-forms",
      },
      items: [
        {
          type: "doc",
          id: "api/get-v-1-company-forms",
          label: "Get all company forms",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/get-v-1-company-form",
          label: "Get a company form",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/get-v-1-company-form-pdf",
          label: "Get a company form pdf",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/put-v-1-company-form-sign",
          label: "Sign a company form",
          className: "api-method put",
        },
      ],
    },
    {
      type: "category",
      label: "Contractor Documents",
      link: {
        type: "doc",
        id: "api/contractor-documents",
      },
      items: [
        {
          type: "doc",
          id: "api/get-v-1-contractor-documents",
          label: "Get all contractor documents",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/get-v-1-contractor-document",
          label: "Get a contractor document",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/get-v-1-contractor-document-pdf",
          label: "Get the contractor document pdf",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/put-v-1-contractor-document-sign",
          label: "Sign a contractor document",
          className: "api-method put",
        },
      ],
    },
    {
      type: "category",
      label: "Employee Forms",
      link: {
        type: "doc",
        id: "api/employee-forms",
      },
      items: [
        {
          type: "doc",
          id: "api/post-v-1-sandbox-generate-w-2",
          label: "Generate a W2 form [DEMO]",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-v-1-employee-forms",
          label: "Get all employee forms",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/get-v-1-employee-form",
          label: "Get an employee form",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/get-v-1-employee-form-pdf",
          label: "Get the employee form pdf",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/put-v-1-employee-form-sign",
          label: "Sign an employee form",
          className: "api-method put",
        },
      ],
    },
    {
      type: "category",
      label: "Company Benefits",
      link: {
        type: "doc",
        id: "api/company-benefits",
      },
      items: [
        {
          type: "doc",
          id: "api/schemas/benefit-type-requirements",
          label: "Benefit-Type-Requirements",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/benefit-summary",
          label: "Benefit-Summary",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/contribution-exclusion",
          label: "Contribution-Exclusion",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/post-v-1-companies-company-id-company-benefits",
          label: "Create a company benefit",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-v-1-companies-company-id-company-benefits",
          label: "Get benefits for a company",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/get-v-1-company-benefits-company-benefit-id",
          label: "Get a company benefit",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/put-v-1-company-benefits-company-benefit-id",
          label: "Update a company benefit",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/delete-v-1-company-benefits-company-benefit-id",
          label: "Delete a company benefit",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/get-v-1-benefits",
          label: "Get all benefits supported by Gusto",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/get-v-1-benefits-benefit-id",
          label: "Get a supported benefit by ID",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/get-v-1-benefits-company-benefit-id-summary",
          label: "Get company benefit summary by company benefit id.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/get-v-1-company-benefits-company-benefit-id-employee-benefits",
          label: "Get all employee benefits for a company benefit",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/put-v-1-company-benefits-company-benefit-id-employee-benefits",
          label: "Bulk update employee benefits for a company benefit",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/get-v-1-company-benefits-company-benefit-id-contribution-exclusions",
          label: "Get contribution exclusions for a company benefit",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/put-v-1-company-benefits-company-benefit-id-contribution-exclusions",
          label: "Update contribution exclusions for a company benefit",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/get-v-1-benefits-benefits-id-requirements",
          label: "Get benefit fields requirements by ID",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Employee Benefits",
      link: {
        type: "doc",
        id: "api/employee-benefits",
      },
      items: [
        {
          type: "doc",
          id: "api/post-v-1-employees-employee-id-employee-benefits",
          label: "Create an employee benefit",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-v-1-employees-employee-id-employee-benefits",
          label: "Get all benefits for an employee",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/get-v-1-employee-benefits-employee-benefit-id",
          label: "Get an employee benefit",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/put-v-1-employee-benefits-employee-benefit-id",
          label: "Update an employee benefit",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/delete-v-1-employee-benefits-employee-benefit-id",
          label: "Delete an employee benefit",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/get-employee-ytd-benefit-amounts-from-different-company",
          label: "Get year-to-date benefit amounts from a different company",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/post-employee-ytd-benefit-amounts-from-different-company",
          label: "Create year-to-date benefit amounts from a different company",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-v-1-employees-employee-uuid-section-603-high-earner-statuses",
          label: "Get all Section 603 high earner statuses for an employee",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/post-v-1-employees-employee-uuid-section-603-high-earner-statuses",
          label: "Create a Section 603 high earner status",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-v-1-employees-employee-uuid-section-603-high-earner-statuses-effective-year",
          label: "Get a Section 603 high earner status for a specific year",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/patch-v-1-employees-employee-uuid-section-603-high-earner-statuses-effective-year",
          label: "Update a Section 603 high earner status",
          className: "api-method patch",
        },
      ],
    },
    {
      type: "category",
      label: "Garnishments",
      link: {
        type: "doc",
        id: "api/garnishments",
      },
      items: [
        {
          type: "doc",
          id: "api/post-v-1-employees-employee-id-garnishments",
          label: "Create a garnishment",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-v-1-employees-employee-id-garnishments",
          label: "Get garnishments for an employee",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/get-v-1-garnishments-garnishment-id",
          label: "Get a garnishment",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/put-v-1-garnishments-garnishment-id",
          label: "Update a garnishment",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/get-v-1-garnishments-child-support",
          label: "Get child support garnishment data",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Federal Tax Details",
      link: {
        type: "doc",
        id: "api/federal-tax-details",
      },
      items: [
        {
          type: "doc",
          id: "api/schemas/federal-tax-details",
          label: "Federal-Tax-Details",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/get-v-1-companies-company-id-federal-tax-details",
          label: "Get Federal Tax Details",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/put-v-1-companies-company-id-federal-tax-details",
          label: "Update Federal Tax Details",
          className: "api-method put",
        },
      ],
    },
    {
      type: "category",
      label: "Industry Selection",
      link: {
        type: "doc",
        id: "api/industry-selection",
      },
      items: [
        {
          type: "doc",
          id: "api/get-v-1-company-industry",
          label: "Get a company industry selection",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/put-v-1-company-industry",
          label: "Update a company industry selection",
          className: "api-method put",
        },
      ],
    },
    {
      type: "category",
      label: "Signatories",
      link: {
        type: "doc",
        id: "api/signatories",
      },
      items: [
        {
          type: "doc",
          id: "api/schemas/signatory",
          label: "Signatory",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/signatory-invite-request",
          label: "Signatory-Invite-Request",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/signatory-create-request",
          label: "Signatory-Create-Request",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/signatory-update-request",
          label: "Signatory-Update-Request",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/post-v-1-company-signatories",
          label: "Create a signatory",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-v-1-companies-company-uuid-signatories",
          label: "Get the signatories for a company",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/post-v-1-companies-company-uuid-signatories-invite",
          label: "Invite a signatory",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/put-v-1-companies-company-uuid-signatories-signatory-uuid",
          label: "Update a signatory",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/delete-v-1-companies-company-uuid-signatories-signatory-uuid",
          label: "Delete a signatory",
          className: "api-method delete",
        },
      ],
    },
    {
      type: "category",
      label: "External Payrolls",
      link: {
        type: "doc",
        id: "api/external-payrolls",
      },
      items: [
        {
          type: "doc",
          id: "api/schemas/external-payroll",
          label: "External-Payroll",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/external-payroll-basic",
          label: "External-Payroll-Basic",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/external-payroll-tax-suggestions",
          label: "External-Payroll-Tax-Suggestions",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/tax-liabilities-selections",
          label: "Tax-Liabilities-Selections",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/post-v-1-external-payroll",
          label: "Create a new external payroll for a company",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-v-1-company-external-payrolls",
          label: "Get external payrolls for a company",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/get-v-1-external-payroll",
          label: "Get an external payroll",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/delete-v-1-external-payroll",
          label: "Delete an external payroll",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/put-v-1-external-payroll",
          label: "Update an external payroll",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/get-v-1-external-payroll-calculate-taxes",
          label: "Get tax suggestions for an external payroll",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/get-v-1-tax-liabilities",
          label: "Get tax liabilities",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/put-v-1-tax-liabilities",
          label: "Update tax liabilities",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/put-v-1-tax-liabilities-finish",
          label: "Finalize tax liabilities options and convert into processed payrolls",
          className: "api-method put",
        },
      ],
    },
    {
      type: "category",
      label: "Tax Requirements",
      link: {
        type: "doc",
        id: "api/tax-requirements",
      },
      items: [
        {
          type: "doc",
          id: "api/get-v-1-companies-company-uuid-tax-requirements-state",
          label: "Get State Tax Requirements",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/put-v-1-companies-company-uuid-tax-requirements-state",
          label: "Update State Tax Requirements",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/get-v-1-companies-company-uuid-tax-requirements",
          label: "Get All Tax Requirement States",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Contractor Forms",
      link: {
        type: "doc",
        id: "api/contractor-forms",
      },
      items: [
        {
          type: "doc",
          id: "api/get-v-1-contractor-forms",
          label: "Get all contractor forms",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/get-v-1-contractor-form",
          label: "Get a contractor form",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/get-v-1-contractor-form-pdf",
          label: "Get the contractor form pdf",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/post-v-1-sandbox-generate-1099",
          label: "Generate a 1099 form [DEMO]",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Time Off Policies",
      link: {
        type: "doc",
        id: "api/time-off-policies",
      },
      items: [
        {
          type: "doc",
          id: "api/post-v-1-payrolls-payroll-id-calculate-accruing-time-off-hours",
          label: "Calculate accruing time off hours",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-v-1-time-off-policies-time-off-policy-uuid",
          label: "Get a time off policy",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/put-v-1-time-off-policies-time-off-policy-uuid",
          label: "Update a time off policy",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/get-v-1-companies-company-uuid-time-off-policies",
          label: "Get all time off policies for a company",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/post-v-1-companies-company-uuid-time-off-policies",
          label: "Create a time off policy",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/put-v-1-time-off-policies-time-off-policy-uuid-add-employees",
          label: "Add employees to a time off policy",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/put-v-1-time-off-policies-time-off-policy-uuid-remove-employees",
          label: "Remove employees from a time off policy",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/put-v-1-time-off-policies-time-off-policy-uuid-balance",
          label: "Update employee time off balances",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/put-v-1-time-off-policies-time-off-policy-uuid-deactivate",
          label: "Deactivate a time off policy",
          className: "api-method put",
        },
      ],
    },
    {
      type: "category",
      label: "Holiday Pay Policies",
      link: {
        type: "doc",
        id: "api/holiday-pay-policies",
      },
      items: [
        {
          type: "doc",
          id: "api/get-v-1-companies-company-uuid-holiday-pay-policy",
          label: "Get a company's holiday pay policy",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/post-v-1-companies-company-uuid-holiday-pay-policy",
          label: "Create a holiday pay policy for a company",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/put-v-1-companies-company-uuid-holiday-pay-policy",
          label: "Update a company's holiday pay policy",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/delete-v-1-companies-company-uuid-holiday-pay-policy",
          label: "Delete a company's holiday pay policy",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/put-v-1-companies-company-uuid-holiday-pay-policy-add",
          label: "Add employees to a company's holiday pay policy",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/put-v-1-companies-company-uuid-holiday-pay-policy-remove",
          label: "Remove employees from a company's holiday pay policy",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/get-companies-company-uuid-paid-holidays",
          label: "Preview a company's paid holidays",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Departments",
      link: {
        type: "doc",
        id: "api/departments",
      },
      items: [
        {
          type: "doc",
          id: "api/post-departments",
          label: "Create a department",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-companies-departments",
          label: "Get all departments of a company",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/get-department",
          label: "Get a department",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/put-departments",
          label: "Update a department",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/delete-department",
          label: "Delete a department",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/put-add-people-to-department",
          label: "Add people to a department",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/put-remove-people-from-department",
          label: "Remove people from a department",
          className: "api-method put",
        },
      ],
    },
    {
      type: "category",
      label: "Reports",
      link: {
        type: "doc",
        id: "api/reports",
      },
      items: [
        {
          type: "doc",
          id: "api/post-companies-company-uuid-reports",
          label: "Create a custom report",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/post-payrolls-payroll-uuid-reports-general-ledger",
          label: "Create a general ledger report",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-reports-request-uuid",
          label: "Get a report",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/get-companies-company-uuid-report-templates-report-type",
          label: "Get a report template",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/post-v-1-companies-company-id-reports-employees-annual-fica-wage",
          label: "Create an employees annual FICA wage report",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Generated Documents",
      link: {
        type: "doc",
        id: "api/generated-documents",
      },
      items: [
        {
          type: "doc",
          id: "api/get-v-1-generated-documents-document-type-request-uuid",
          label: "Get a generated document",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Notifications",
      link: {
        type: "doc",
        id: "api/notifications",
      },
      items: [
        {
          type: "doc",
          id: "api/get-notifications-notification-uuid",
          label: "Get a notification's details",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/get-company-notifications",
          label: "Get notifications for company",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Webhooks",
      link: {
        type: "doc",
        id: "api/webhooks",
      },
      items: [
        {
          type: "doc",
          id: "api/schemas/webhook-subscription",
          label: "Webhook-Subscription",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/post-v-1-webhook-subscription",
          label: "Create a webhook subscription",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-v-1-webhook-subscriptions",
          label: "List webhook subscriptions",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/put-v-1-webhook-subscription-uuid",
          label: "Update a webhook subscription",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/get-v-1-webhook-subscription-uuid",
          label: "Get a webhook subscription",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/delete-v-1-webhook-subscription-uuid",
          label: "Delete a webhook subscription",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/put-v-1-verify-webhook-subscription-uuid",
          label: "Verify the webhook subscription",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/get-v-1-webhook-subscription-verification-token-uuid",
          label: "Request the webhook subscription verification_token",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/get-v-1-webhooks-health-check",
          label: "Get the webhooks health status",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Events",
      link: {
        type: "doc",
        id: "api/events",
      },
      items: [
        {
          type: "doc",
          id: "api/get-events",
          label: "Get all events",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Invoices",
      link: {
        type: "doc",
        id: "api/invoices",
      },
      items: [
        {
          type: "doc",
          id: "api/get-invoices-invoice-period",
          label: "Retrieve invoicing data for companies",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Recovery Cases",
      link: {
        type: "doc",
        id: "api/recovery-cases",
      },
      items: [
        {
          type: "doc",
          id: "api/get-recovery-cases",
          label: "Get all recovery cases for a company",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/redebit-recovery-case",
          label: "Initiate a redebit for a recovery case",
          className: "api-method put",
        },
      ],
    },
    {
      type: "category",
      label: "Company Attachment",
      link: {
        type: "doc",
        id: "api/company-attachment",
      },
      items: [
        {
          type: "doc",
          id: "api/schemas/company-attachment",
          label: "Company-Attachment",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/get-v-1-companies-attachment",
          label: "Get Company Attachment Details",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/get-v-1-companies-attachment-url",
          label: "Get a temporary url to download the Company Attachment file",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/get-v-1-companies-attachments",
          label: "Get List of Company Attachments",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/post-v-1-companies-attachment",
          label: "Create Company Attachment and Upload File",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Wire In Requests",
      link: {
        type: "doc",
        id: "api/wire-in-requests",
      },
      items: [
        {
          type: "doc",
          id: "api/get-wire-in-requests-wire-in-request-uuid",
          label: "Get a single Wire In Request",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/put-wire-in-requests-wire-in-request-uuid",
          label: "Submit a wire in request",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/get-companies-company-uuid-wire-in-request-uuid",
          label: "Get all Wire In Requests for a company",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "ACH Transactions",
      link: {
        type: "doc",
        id: "api/ach-transactions",
      },
      items: [
        {
          type: "doc",
          id: "api/get-ach-transactions",
          label: "Get all ACH transactions for a company",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Information Requests",
      link: {
        type: "doc",
        id: "api/information-requests",
      },
      items: [
        {
          type: "doc",
          id: "api/get-information-requests",
          label: "Get all information requests for a company",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/submit-information-request",
          label: "Submit information request responses",
          className: "api-method put",
        },
      ],
    },
    {
      type: "category",
      label: "Salary Estimates",
      link: {
        type: "doc",
        id: "api/salary-estimates",
      },
      items: [
        {
          type: "doc",
          id: "api/post-v-1-employees-employee-id-salary-estimates",
          label: "Create a salary estimate for an employee",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-v-1-salary-estimates-id",
          label: "Get a salary estimate",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/put-v-1-salary-estimates-id",
          label: "Update a salary estimate",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/post-v-1-salary-estimates-uuid-accept",
          label: "Accept a salary estimate",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-v-1-salary-estimates-occupations",
          label: "Search for BLS occupations",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Reimbursements",
      link: {
        type: "doc",
        id: "api/reimbursements",
      },
      items: [
        {
          type: "doc",
          id: "api/get-v-1-employees-employee-id-recurring-reimbursements",
          label: "Get recurring reimbursements for an employee",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/post-v-1-employees-employee-id-recurring-reimbursements",
          label: "Create a recurring reimbursement",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-v-1-recurring-reimbursements",
          label: "Get a recurring reimbursement",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/put-v-1-recurring-reimbursements",
          label: "Update a recurring reimbursement",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/delete-v-1-recurring-reimbursements",
          label: "Delete a recurring reimbursement",
          className: "api-method delete",
        },
      ],
    },
    {
      type: "category",
      label: "People Batches",
      link: {
        type: "doc",
        id: "api/people-batches",
      },
      items: [
        {
          type: "doc",
          id: "api/post-v-1-companies-company-id-people-batches",
          label: "Create a people batch",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-v-1-people-batches-people-batch-uuid",
          label: "Get a people batch",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Forms",
      items: [
        {
          type: "doc",
          id: "api/schemas/form",
          label: "Form",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/form",
          label: "Form",
          className: "schema",
        },
      ],
    },
    {
      type: "category",
      label: "Documents",
      items: [
        {
          type: "doc",
          id: "api/schemas/document",
          label: "Document",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/document-signed",
          label: "Document Signed",
          className: "schema",
        },
      ],
    },
    {
      type: "category",
      label: "Industry",
      items: [
        {
          type: "doc",
          id: "api/schemas/industry",
          label: "Industry",
          className: "schema",
        },
      ],
    },
    {
      type: "category",
      label: "Admins",
      items: [
        {
          type: "doc",
          id: "api/schemas/admin",
          label: "Admin",
          className: "schema",
        },
      ],
    },
    {
      type: "category",
      label: "Contractor",
      items: [
        {
          type: "doc",
          id: "api/schemas/contractor-onboarding-status",
          label: "Contractor-Onboarding-Status",
          className: "schema",
        },
      ],
    },
    {
      type: "category",
      label: "Company Bank Accounts",
      items: [
        {
          type: "doc",
          id: "api/schemas/company-bank-account",
          label: "Company-Bank-Account",
          className: "schema",
        },
      ],
    },
    {
      type: "category",
      label: "Custom Fields",
      items: [
        {
          type: "doc",
          id: "api/schemas/company-custom-field",
          label: "Company-Custom-Field",
          className: "schema",
        },
      ],
    },
  ],
};

export default sidebar.apisidebar;
