export * from '@/components'
export * from '@/contexts'
export { componentEvents } from '@/shared/constants'
export type {
  BeforeCreateRequestHook,
  BeforeRequestHook,
  AfterSuccessHook,
  AfterErrorHook,
  BeforeCreateRequestContext,
  BeforeRequestContext,
  AfterSuccessContext,
  AfterErrorContext,
  SDKHooks,
} from '@/types/hooks'
export type { SDKError, SDKErrorCategory, SDKFieldError } from '@/types/sdkError'
export { normalizeToSDKError, SDKInternalError } from '@/types/sdkError'
export type {
  ObservabilityHook,
  ObservabilityError,
  ObservabilityMetric,
  ObservabilityMetricUnit,
  SanitizationConfig,
} from '@/types/observability'
export type {
  ConfirmWireDetailsProps,
  ConfirmWireDetailsComponentType,
} from '@/components/Payroll/ConfirmWireDetails'

// Partner hook infrastructure
export {
  composeErrorHandler,
  collectErrors,
  SDKFormProvider,
  composeSubmitHandler,
  useFieldErrorMessage,
  useDeriveFieldsMetadata,
  withOptions,
  FormFieldsMetadataProvider,
  TextInputHookField,
  SelectHookField,
  CheckboxHookField,
  NumberInputHookField,
  DatePickerHookField,
  RadioGroupHookField,
  SwitchHookField,
} from '@/partner-hook-utils'
export type {
  MixedErrorSource,
  SubmitStateForErrorHandling,
  HookFormInternals,
  HookLoadingResult,
  HookSubmitResult,
  HookErrorHandling,
  BaseHookReady,
  BaseFormHookReady,
  FormHookResult,
  FieldMetadata,
  FieldMetadataWithOptions,
  FieldsMetadata,
  ValidationMessages,
  BaseFieldProps,
  HookFieldProps,
  TextInputHookFieldProps,
  SelectHookFieldProps,
  CheckboxHookFieldProps,
  NumberInputHookFieldProps,
  DatePickerHookFieldProps,
  RadioGroupHookFieldProps,
  SwitchHookFieldProps,
  TextInputProps,
  SelectProps,
  SelectOption,
  CheckboxProps,
  NumberInputProps,
  DatePickerProps,
  RadioGroupProps,
  RadioGroupOption,
  SwitchProps,
  FormFieldsMetadataContextValue,
} from '@/partner-hook-utils'

// Domain hooks - Employee
export {
  useCompensationForm,
  CompensationErrorCodes,
  createCompensationSchema,
} from '@/components/Employee/Compensation/shared/useCompensationForm'
export type {
  CompensationSubmitCallbacks,
  CompensationSubmitOptions,
  UseCompensationFormProps,
  UseCompensationFormResult,
  UseCompensationFormReady,
  CompensationFieldsMetadata,
  CompensationFormFields,
  CompensationErrorCode,
  CompensationOptionalFieldsToRequire,
  CompensationFormData,
  CompensationFormOutputs,
  RequiredValidation,
  RateValidation,
  StartDateFieldProps,
  JobTitleFieldProps,
  FlsaStatusFieldProps,
  RateFieldProps,
  PaymentUnitFieldProps,
  AdjustForMinimumWageFieldProps,
  MinimumWageIdFieldProps,
  TwoPercentShareholderFieldProps,
  StateWcCoveredFieldProps,
  StateWcClassCodeFieldProps,
} from '@/components/Employee/Compensation/shared/useCompensationForm'

export {
  useEmployeeDetailsForm,
  EmployeeDetailsErrorCodes,
  createEmployeeDetailsSchema,
} from '@/components/Employee/Profile/shared/useEmployeeDetailsForm'
export type {
  EmployeeDetailsSubmitCallbacks,
  EmployeeDetailsOptionalFieldsToRequire,
  UseEmployeeDetailsFormProps,
  UseEmployeeDetailsFormResult,
  UseEmployeeDetailsFormReady,
  EmployeeDetailsFieldsMetadata,
  EmployeeDetailsFormFields,
  EmployeeDetailsErrorCode,
  EmployeeDetailsFormData,
  EmployeeDetailsFormOutputs,
  EmployeeDetailsField,
  EmployeeDetailsRequiredValidation,
  NameValidation,
  EmailValidation,
  SsnValidation,
  FirstNameFieldProps,
  MiddleInitialFieldProps,
  LastNameFieldProps,
  EmailFieldProps,
  DateOfBirthFieldProps,
  SsnFieldProps,
  SelfOnboardingFieldProps,
} from '@/components/Employee/Profile/shared/useEmployeeDetailsForm'

export {
  useWorkAddressForm,
  useCurrentWorkAddressForm,
  WorkAddressErrorCodes,
  createWorkAddressSchema,
} from '@/components/Employee/Profile/shared/useWorkAddressForm'
export type {
  WorkAddressSubmitCallbacks,
  WorkAddressSubmitOptions,
  WorkAddressOptionalFieldsToRequire,
  UseCurrentWorkAddressFormProps,
  UseWorkAddressFormProps,
  UseWorkAddressFormResult,
  UseWorkAddressFormReady,
  WorkAddressFieldsMetadata,
  WorkAddressFormFields,
  WorkAddressErrorCode,
  WorkAddressFormData,
  WorkAddressFormOutputs,
  WorkAddressField,
  WorkAddressRequiredValidation,
  LocationFieldProps,
  EffectiveDateFieldProps,
} from '@/components/Employee/Profile/shared/useWorkAddressForm'

export {
  useHomeAddressForm,
  useCurrentHomeAddressForm,
  HomeAddressErrorCodes,
  createHomeAddressSchema,
} from '@/components/Employee/Profile/shared/useHomeAddressForm'
export type {
  HomeAddressSubmitOptions,
  HomeAddressOptionalFieldsToRequire,
  UseHomeAddressFormProps,
  UseCurrentHomeAddressFormProps,
  UseHomeAddressFormResult,
  UseHomeAddressFormReady,
  HomeAddressFieldsMetadata,
  HomeAddressFormFields,
  HomeAddressErrorCode,
  HomeAddressFormData,
  HomeAddressFormOutputs,
  HomeAddressField,
  HomeAddressRequiredValidation,
  ZipValidation,
  Street1FieldProps,
  Street2FieldProps,
  CityFieldProps,
  StateFieldProps,
  ZipFieldProps,
  CourtesyWithholdingFieldProps,
  HomeAddressEffectiveDateFieldProps,
} from '@/components/Employee/Profile/shared/useHomeAddressForm'

export {
  useSignEmployeeForm,
  SignEmployeeFormErrorCodes,
  createSignEmployeeFormSchema,
  MAX_PREPARERS,
  PREPARER_FIELDS_BY_INDEX,
  preparerFieldName,
} from '@/components/Employee/DocumentSigner/shared/useSignEmployeeForm'
export type {
  UseSignEmployeeFormProps,
  UseSignEmployeeFormResult,
  UseSignEmployeeFormReady,
  SignEmployeeFormFieldComponents,
  SignEmployeeFormFieldsMetadata,
  SignEmployeeFormFields,
  PreparerFieldGroup,
  SignEmployeeFormErrorCode,
  SignEmployeeFormData,
  SignEmployeeFormOutputs,
  SignEmployeeFormField,
  PreparerIndex,
  PreparerFieldSuffix,
  SignEmployeeFormRequiredValidation,
  SignatureFieldProps as SignEmployeeFormSignatureFieldProps,
  ConfirmSignatureFieldProps as SignEmployeeFormConfirmSignatureFieldProps,
  UsedPreparerFieldProps,
  PreparerTextFieldProps,
  PreparerCheckboxFieldProps,
} from '@/components/Employee/DocumentSigner/shared/useSignEmployeeForm'

// Domain hooks - Company
export {
  usePayScheduleForm,
  PayScheduleErrorCodes,
  createPayScheduleSchema,
} from '@/components/Company/PaySchedule/shared/usePayScheduleForm'
export type {
  PayScheduleOptionalFieldsToRequire,
  UsePayScheduleFormProps,
  UsePayScheduleFormResult,
  UsePayScheduleFormReady,
  PayScheduleFieldsMetadata,
  PayScheduleFormFields,
  PayScheduleErrorCode,
  PayScheduleFormData,
  PayScheduleFormOutputs,
  PayScheduleField,
  PayScheduleFrequency,
  PayScheduleRequiredValidation,
  DayValidation,
  CustomNameFieldProps,
  FrequencyFieldProps,
  CustomTwicePerMonthFieldProps,
  AnchorPayDateFieldProps,
  AnchorEndOfPayPeriodFieldProps,
  Day1FieldProps,
  Day2FieldProps,
} from '@/components/Company/PaySchedule/shared/usePayScheduleForm'

export {
  useSignCompanyForm,
  SignCompanyFormErrorCodes,
  createSignCompanyFormSchema,
} from '@/components/Company/DocumentSigner/shared/useSignCompanyForm'
export type {
  SignCompanyFormOptionalFieldsToRequire,
  UseSignCompanyFormProps,
  UseSignCompanyFormResult,
  UseSignCompanyFormReady,
  SignCompanyFormFieldsMetadata,
  SignCompanyFormFields,
  SignCompanyFormErrorCode,
  SignCompanyFormData,
  SignCompanyFormOutputs,
  SignCompanyFormField,
  SignCompanyFormRequiredValidation,
  SignatureFieldProps,
  ConfirmSignatureFieldProps,
} from '@/components/Company/DocumentSigner/shared/useSignCompanyForm'
