name: Unpublish an old NPM package
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to unpublish'
        required: true
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v6
      - name: Authenticate with Cloudsmith via OIDC
        uses: cloudsmith-io/cloudsmith-cli-action@v2
        with:
          oidc-namespace: 'gusto'
          oidc-service-slug: 'gusto-cloudsmith-write-svc-01'
          oidc-auth-only: 'true'
      - uses: actions/setup-node@v6
        with:
          node-version-file: '.nvmrc'
          registry-url: 'https://cloudsmith.io/gusto/gusto'
      - run: npm unpublish @gusto/embedded-react-sdk@${{ github.event.inputs.version }}
        env:
          NODE_AUTH_TOKEN: ${{ env.CLOUDSMITH_API_KEY }}
